<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/compute/v1/compute.proto

namespace Google\Cloud\Compute\V1\Commitment;

use UnexpectedValueException;

/**
 * Protobuf type <code>google.cloud.compute.v1.Commitment.Plan</code>
 */
class Plan
{
    /**
     * Generated from protobuf enum <code>INVALID = 0;</code>
     */
    const INVALID = 0;
    /**
     * Generated from protobuf enum <code>THIRTY_SIX_MONTH = 1;</code>
     */
    const THIRTY_SIX_MONTH = 1;
    /**
     * Generated from protobuf enum <code>TWELVE_MONTH = 2;</code>
     */
    const TWELVE_MONTH = 2;

    private static $valueToName = [
        self::INVALID => 'INVALID',
        self::THIRTY_SIX_MONTH => 'THIRTY_SIX_MONTH',
        self::TWELVE_MONTH => 'TWELVE_MONTH',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Plan::class, \Google\Cloud\Compute\V1\Commitment_Plan::class);

