<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/compute/v1/compute.proto

namespace Google\Cloud\Compute\V1\InterconnectOutageNotification;

use UnexpectedValueException;

/**
 * Protobuf type <code>google.cloud.compute.v1.InterconnectOutageNotification.IssueType</code>
 */
class IssueType
{
    /**
     * Generated from protobuf enum <code>IT_OUTAGE = 0;</code>
     */
    const IT_OUTAGE = 0;
    /**
     * Generated from protobuf enum <code>IT_PARTIAL_OUTAGE = 1;</code>
     */
    const IT_PARTIAL_OUTAGE = 1;
    /**
     * Generated from protobuf enum <code>OUTAGE = 2;</code>
     */
    const OUTAGE = 2;
    /**
     * Generated from protobuf enum <code>PARTIAL_OUTAGE = 3;</code>
     */
    const PARTIAL_OUTAGE = 3;

    private static $valueToName = [
        self::IT_OUTAGE => 'IT_OUTAGE',
        self::IT_PARTIAL_OUTAGE => 'IT_PARTIAL_OUTAGE',
        self::OUTAGE => 'OUTAGE',
        self::PARTIAL_OUTAGE => 'PARTIAL_OUTAGE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(IssueType::class, \Google\Cloud\Compute\V1\InterconnectOutageNotification_IssueType::class);

