<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/compute/v1/compute.proto

namespace Google\Cloud\Compute\V1\InterconnectOutageNotification;

use UnexpectedValueException;

/**
 * Protobuf type <code>google.cloud.compute.v1.InterconnectOutageNotification.State</code>
 */
class State
{
    /**
     * Generated from protobuf enum <code>ACTIVE = 0;</code>
     */
    const ACTIVE = 0;
    /**
     * Generated from protobuf enum <code>CANCELLED = 1;</code>
     */
    const CANCELLED = 1;
    /**
     * Generated from protobuf enum <code>COMPLETED = 2;</code>
     */
    const COMPLETED = 2;
    /**
     * Generated from protobuf enum <code>NS_ACTIVE = 3;</code>
     */
    const NS_ACTIVE = 3;
    /**
     * Generated from protobuf enum <code>NS_CANCELED = 4;</code>
     */
    const NS_CANCELED = 4;

    private static $valueToName = [
        self::ACTIVE => 'ACTIVE',
        self::CANCELLED => 'CANCELLED',
        self::COMPLETED => 'COMPLETED',
        self::NS_ACTIVE => 'NS_ACTIVE',
        self::NS_CANCELED => 'NS_CANCELED',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(State::class, \Google\Cloud\Compute\V1\InterconnectOutageNotification_State::class);

