<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/compute/v1/compute.proto

namespace Google\Cloud\Compute\V1\RouterNat;

use UnexpectedValueException;

/**
 * Protobuf type <code>google.cloud.compute.v1.RouterNat.NatIpAllocateOption</code>
 */
class NatIpAllocateOption
{
    /**
     * Generated from protobuf enum <code>AUTO_ONLY = 0;</code>
     */
    const AUTO_ONLY = 0;
    /**
     * Generated from protobuf enum <code>MANUAL_ONLY = 1;</code>
     */
    const MANUAL_ONLY = 1;

    private static $valueToName = [
        self::AUTO_ONLY => 'AUTO_ONLY',
        self::MANUAL_ONLY => 'MANUAL_ONLY',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(NatIpAllocateOption::class, \Google\Cloud\Compute\V1\RouterNat_NatIpAllocateOption::class);

