<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/compute/v1/compute.proto

namespace Google\Cloud\Compute\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>google.cloud.compute.v1.Address</code>
 */
class Address extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string address = 1;</code>
     */
    protected $address = '';
    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.Address.AddressType address_type = 2;</code>
     */
    protected $address_type = 0;
    /**
     * Generated from protobuf field <code>string creation_timestamp = 3;</code>
     */
    protected $creation_timestamp = '';
    /**
     * Generated from protobuf field <code>string description = 4;</code>
     */
    protected $description = '';
    /**
     * Generated from protobuf field <code>string id = 5;</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.Address.IpVersion ip_version = 6;</code>
     */
    protected $ip_version = 0;
    /**
     * Generated from protobuf field <code>string kind = 7;</code>
     */
    protected $kind = '';
    /**
     * Generated from protobuf field <code>string name = 8;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>string network = 9;</code>
     */
    protected $network = '';
    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.Address.NetworkTier network_tier = 10;</code>
     */
    protected $network_tier = 0;
    /**
     * Generated from protobuf field <code>int32 prefix_length = 11;</code>
     */
    protected $prefix_length = 0;
    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.Address.Purpose purpose = 12;</code>
     */
    protected $purpose = 0;
    /**
     * Generated from protobuf field <code>string region = 13;</code>
     */
    protected $region = '';
    /**
     * Generated from protobuf field <code>string self_link = 14;</code>
     */
    protected $self_link = '';
    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.Address.Status status = 15;</code>
     */
    protected $status = 0;
    /**
     * Generated from protobuf field <code>string subnetwork = 16;</code>
     */
    protected $subnetwork = '';
    /**
     * Generated from protobuf field <code>repeated string users = 17;</code>
     */
    private $users;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $address
     *     @type int $address_type
     *     @type string $creation_timestamp
     *     @type string $description
     *     @type string $id
     *     @type int $ip_version
     *     @type string $kind
     *     @type string $name
     *     @type string $network
     *     @type int $network_tier
     *     @type int $prefix_length
     *     @type int $purpose
     *     @type string $region
     *     @type string $self_link
     *     @type int $status
     *     @type string $subnetwork
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $users
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Cloud\Compute\V1\Compute::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string address = 1;</code>
     * @return string
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * Generated from protobuf field <code>string address = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.Address.AddressType address_type = 2;</code>
     * @return int
     */
    public function getAddressType()
    {
        return $this->address_type;
    }

    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.Address.AddressType address_type = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setAddressType($var)
    {
        GPBUtil::checkEnum($var, \Google\Cloud\Compute\V1\Address_AddressType::class);
        $this->address_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string creation_timestamp = 3;</code>
     * @return string
     */
    public function getCreationTimestamp()
    {
        return $this->creation_timestamp;
    }

    /**
     * Generated from protobuf field <code>string creation_timestamp = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCreationTimestamp($var)
    {
        GPBUtil::checkString($var, True);
        $this->creation_timestamp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string description = 4;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>string description = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string id = 5;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.Address.IpVersion ip_version = 6;</code>
     * @return int
     */
    public function getIpVersion()
    {
        return $this->ip_version;
    }

    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.Address.IpVersion ip_version = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setIpVersion($var)
    {
        GPBUtil::checkEnum($var, \Google\Cloud\Compute\V1\Address_IpVersion::class);
        $this->ip_version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string kind = 7;</code>
     * @return string
     */
    public function getKind()
    {
        return $this->kind;
    }

    /**
     * Generated from protobuf field <code>string kind = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setKind($var)
    {
        GPBUtil::checkString($var, True);
        $this->kind = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 8;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string network = 9;</code>
     * @return string
     */
    public function getNetwork()
    {
        return $this->network;
    }

    /**
     * Generated from protobuf field <code>string network = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setNetwork($var)
    {
        GPBUtil::checkString($var, True);
        $this->network = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.Address.NetworkTier network_tier = 10;</code>
     * @return int
     */
    public function getNetworkTier()
    {
        return $this->network_tier;
    }

    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.Address.NetworkTier network_tier = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setNetworkTier($var)
    {
        GPBUtil::checkEnum($var, \Google\Cloud\Compute\V1\Address_NetworkTier::class);
        $this->network_tier = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 prefix_length = 11;</code>
     * @return int
     */
    public function getPrefixLength()
    {
        return $this->prefix_length;
    }

    /**
     * Generated from protobuf field <code>int32 prefix_length = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setPrefixLength($var)
    {
        GPBUtil::checkInt32($var);
        $this->prefix_length = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.Address.Purpose purpose = 12;</code>
     * @return int
     */
    public function getPurpose()
    {
        return $this->purpose;
    }

    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.Address.Purpose purpose = 12;</code>
     * @param int $var
     * @return $this
     */
    public function setPurpose($var)
    {
        GPBUtil::checkEnum($var, \Google\Cloud\Compute\V1\Address_Purpose::class);
        $this->purpose = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string region = 13;</code>
     * @return string
     */
    public function getRegion()
    {
        return $this->region;
    }

    /**
     * Generated from protobuf field <code>string region = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setRegion($var)
    {
        GPBUtil::checkString($var, True);
        $this->region = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string self_link = 14;</code>
     * @return string
     */
    public function getSelfLink()
    {
        return $this->self_link;
    }

    /**
     * Generated from protobuf field <code>string self_link = 14;</code>
     * @param string $var
     * @return $this
     */
    public function setSelfLink($var)
    {
        GPBUtil::checkString($var, True);
        $this->self_link = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.Address.Status status = 15;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.Address.Status status = 15;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \Google\Cloud\Compute\V1\Address_Status::class);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string subnetwork = 16;</code>
     * @return string
     */
    public function getSubnetwork()
    {
        return $this->subnetwork;
    }

    /**
     * Generated from protobuf field <code>string subnetwork = 16;</code>
     * @param string $var
     * @return $this
     */
    public function setSubnetwork($var)
    {
        GPBUtil::checkString($var, True);
        $this->subnetwork = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string users = 17;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUsers()
    {
        return $this->users;
    }

    /**
     * Generated from protobuf field <code>repeated string users = 17;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUsers($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->users = $arr;

        return $this;
    }

}

