<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/compute/v1/compute.proto

namespace Google\Cloud\Compute\V1;

if (false) {
    /**
     * This class is deprecated. Use Google\Cloud\Compute\V1\AllocationSpecificSKUAllocationReservedInstanceProperties\MaintenanceInterval instead.
     * @deprecated
     */
    class AllocationSpecificSKUAllocationReservedInstanceProperties_MaintenanceInterval {}
}
class_exists(AllocationSpecificSKUAllocationReservedInstanceProperties\MaintenanceInterval::class);
@trigger_error('Google\Cloud\Compute\V1\AllocationSpecificSKUAllocationReservedInstanceProperties_MaintenanceInterval is deprecated and will be removed in the next major release. Use Google\Cloud\Compute\V1\AllocationSpecificSKUAllocationReservedInstanceProperties\MaintenanceInterval instead', E_USER_DEPRECATED);

