<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/compute/v1/compute.proto

namespace Google\Cloud\Compute\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>google.cloud.compute.v1.AutoscalingPolicyLoadBalancingUtilization</code>
 */
class AutoscalingPolicyLoadBalancingUtilization extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>double utilization_target = 1;</code>
     */
    protected $utilization_target = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $utilization_target
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Cloud\Compute\V1\Compute::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>double utilization_target = 1;</code>
     * @return float
     */
    public function getUtilizationTarget()
    {
        return $this->utilization_target;
    }

    /**
     * Generated from protobuf field <code>double utilization_target = 1;</code>
     * @param float $var
     * @return $this
     */
    public function setUtilizationTarget($var)
    {
        GPBUtil::checkDouble($var);
        $this->utilization_target = $var;

        return $this;
    }

}

