<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/compute/v1/compute.proto

namespace Google\Cloud\Compute\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>google.cloud.compute.v1.BackendServiceLogConfig</code>
 */
class BackendServiceLogConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool enable = 1;</code>
     */
    protected $enable = false;
    /**
     * Generated from protobuf field <code>float sample_rate = 2;</code>
     */
    protected $sample_rate = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $enable
     *     @type float $sample_rate
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Cloud\Compute\V1\Compute::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool enable = 1;</code>
     * @return bool
     */
    public function getEnable()
    {
        return $this->enable;
    }

    /**
     * Generated from protobuf field <code>bool enable = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setEnable($var)
    {
        GPBUtil::checkBool($var);
        $this->enable = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float sample_rate = 2;</code>
     * @return float
     */
    public function getSampleRate()
    {
        return $this->sample_rate;
    }

    /**
     * Generated from protobuf field <code>float sample_rate = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setSampleRate($var)
    {
        GPBUtil::checkFloat($var);
        $this->sample_rate = $var;

        return $this;
    }

}

