<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/compute/v1/compute.proto

namespace Google\Cloud\Compute\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>google.cloud.compute.v1.Backend</code>
 */
class Backend extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.Backend.BalancingMode balancing_mode = 1;</code>
     */
    protected $balancing_mode = 0;
    /**
     * Generated from protobuf field <code>float capacity_scaler = 2;</code>
     */
    protected $capacity_scaler = 0.0;
    /**
     * Generated from protobuf field <code>string description = 3;</code>
     */
    protected $description = '';
    /**
     * Generated from protobuf field <code>bool failover = 4;</code>
     */
    protected $failover = false;
    /**
     * Generated from protobuf field <code>string group = 5;</code>
     */
    protected $group = '';
    /**
     * Generated from protobuf field <code>int32 max_connections = 6;</code>
     */
    protected $max_connections = 0;
    /**
     * Generated from protobuf field <code>int32 max_connections_per_endpoint = 7;</code>
     */
    protected $max_connections_per_endpoint = 0;
    /**
     * Generated from protobuf field <code>int32 max_connections_per_instance = 8;</code>
     */
    protected $max_connections_per_instance = 0;
    /**
     * Generated from protobuf field <code>int32 max_rate = 9;</code>
     */
    protected $max_rate = 0;
    /**
     * Generated from protobuf field <code>float max_rate_per_endpoint = 10;</code>
     */
    protected $max_rate_per_endpoint = 0.0;
    /**
     * Generated from protobuf field <code>float max_rate_per_instance = 11;</code>
     */
    protected $max_rate_per_instance = 0.0;
    /**
     * Generated from protobuf field <code>float max_utilization = 12;</code>
     */
    protected $max_utilization = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $balancing_mode
     *     @type float $capacity_scaler
     *     @type string $description
     *     @type bool $failover
     *     @type string $group
     *     @type int $max_connections
     *     @type int $max_connections_per_endpoint
     *     @type int $max_connections_per_instance
     *     @type int $max_rate
     *     @type float $max_rate_per_endpoint
     *     @type float $max_rate_per_instance
     *     @type float $max_utilization
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Cloud\Compute\V1\Compute::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.Backend.BalancingMode balancing_mode = 1;</code>
     * @return int
     */
    public function getBalancingMode()
    {
        return $this->balancing_mode;
    }

    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.Backend.BalancingMode balancing_mode = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setBalancingMode($var)
    {
        GPBUtil::checkEnum($var, \Google\Cloud\Compute\V1\Backend_BalancingMode::class);
        $this->balancing_mode = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float capacity_scaler = 2;</code>
     * @return float
     */
    public function getCapacityScaler()
    {
        return $this->capacity_scaler;
    }

    /**
     * Generated from protobuf field <code>float capacity_scaler = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setCapacityScaler($var)
    {
        GPBUtil::checkFloat($var);
        $this->capacity_scaler = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string description = 3;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>string description = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool failover = 4;</code>
     * @return bool
     */
    public function getFailover()
    {
        return $this->failover;
    }

    /**
     * Generated from protobuf field <code>bool failover = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setFailover($var)
    {
        GPBUtil::checkBool($var);
        $this->failover = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string group = 5;</code>
     * @return string
     */
    public function getGroup()
    {
        return $this->group;
    }

    /**
     * Generated from protobuf field <code>string group = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setGroup($var)
    {
        GPBUtil::checkString($var, True);
        $this->group = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 max_connections = 6;</code>
     * @return int
     */
    public function getMaxConnections()
    {
        return $this->max_connections;
    }

    /**
     * Generated from protobuf field <code>int32 max_connections = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setMaxConnections($var)
    {
        GPBUtil::checkInt32($var);
        $this->max_connections = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 max_connections_per_endpoint = 7;</code>
     * @return int
     */
    public function getMaxConnectionsPerEndpoint()
    {
        return $this->max_connections_per_endpoint;
    }

    /**
     * Generated from protobuf field <code>int32 max_connections_per_endpoint = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setMaxConnectionsPerEndpoint($var)
    {
        GPBUtil::checkInt32($var);
        $this->max_connections_per_endpoint = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 max_connections_per_instance = 8;</code>
     * @return int
     */
    public function getMaxConnectionsPerInstance()
    {
        return $this->max_connections_per_instance;
    }

    /**
     * Generated from protobuf field <code>int32 max_connections_per_instance = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setMaxConnectionsPerInstance($var)
    {
        GPBUtil::checkInt32($var);
        $this->max_connections_per_instance = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 max_rate = 9;</code>
     * @return int
     */
    public function getMaxRate()
    {
        return $this->max_rate;
    }

    /**
     * Generated from protobuf field <code>int32 max_rate = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setMaxRate($var)
    {
        GPBUtil::checkInt32($var);
        $this->max_rate = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float max_rate_per_endpoint = 10;</code>
     * @return float
     */
    public function getMaxRatePerEndpoint()
    {
        return $this->max_rate_per_endpoint;
    }

    /**
     * Generated from protobuf field <code>float max_rate_per_endpoint = 10;</code>
     * @param float $var
     * @return $this
     */
    public function setMaxRatePerEndpoint($var)
    {
        GPBUtil::checkFloat($var);
        $this->max_rate_per_endpoint = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float max_rate_per_instance = 11;</code>
     * @return float
     */
    public function getMaxRatePerInstance()
    {
        return $this->max_rate_per_instance;
    }

    /**
     * Generated from protobuf field <code>float max_rate_per_instance = 11;</code>
     * @param float $var
     * @return $this
     */
    public function setMaxRatePerInstance($var)
    {
        GPBUtil::checkFloat($var);
        $this->max_rate_per_instance = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float max_utilization = 12;</code>
     * @return float
     */
    public function getMaxUtilization()
    {
        return $this->max_utilization;
    }

    /**
     * Generated from protobuf field <code>float max_utilization = 12;</code>
     * @param float $var
     * @return $this
     */
    public function setMaxUtilization($var)
    {
        GPBUtil::checkFloat($var);
        $this->max_utilization = $var;

        return $this;
    }

}

