<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/compute/v1/compute.proto

namespace Google\Cloud\Compute\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>google.cloud.compute.v1.CircuitBreakers</code>
 */
class CircuitBreakers extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 max_connections = 1;</code>
     */
    protected $max_connections = 0;
    /**
     * Generated from protobuf field <code>int32 max_pending_requests = 2;</code>
     */
    protected $max_pending_requests = 0;
    /**
     * Generated from protobuf field <code>int32 max_requests = 3;</code>
     */
    protected $max_requests = 0;
    /**
     * Generated from protobuf field <code>int32 max_requests_per_connection = 4;</code>
     */
    protected $max_requests_per_connection = 0;
    /**
     * Generated from protobuf field <code>int32 max_retries = 5;</code>
     */
    protected $max_retries = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $max_connections
     *     @type int $max_pending_requests
     *     @type int $max_requests
     *     @type int $max_requests_per_connection
     *     @type int $max_retries
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Cloud\Compute\V1\Compute::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 max_connections = 1;</code>
     * @return int
     */
    public function getMaxConnections()
    {
        return $this->max_connections;
    }

    /**
     * Generated from protobuf field <code>int32 max_connections = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setMaxConnections($var)
    {
        GPBUtil::checkInt32($var);
        $this->max_connections = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 max_pending_requests = 2;</code>
     * @return int
     */
    public function getMaxPendingRequests()
    {
        return $this->max_pending_requests;
    }

    /**
     * Generated from protobuf field <code>int32 max_pending_requests = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setMaxPendingRequests($var)
    {
        GPBUtil::checkInt32($var);
        $this->max_pending_requests = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 max_requests = 3;</code>
     * @return int
     */
    public function getMaxRequests()
    {
        return $this->max_requests;
    }

    /**
     * Generated from protobuf field <code>int32 max_requests = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setMaxRequests($var)
    {
        GPBUtil::checkInt32($var);
        $this->max_requests = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 max_requests_per_connection = 4;</code>
     * @return int
     */
    public function getMaxRequestsPerConnection()
    {
        return $this->max_requests_per_connection;
    }

    /**
     * Generated from protobuf field <code>int32 max_requests_per_connection = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setMaxRequestsPerConnection($var)
    {
        GPBUtil::checkInt32($var);
        $this->max_requests_per_connection = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 max_retries = 5;</code>
     * @return int
     */
    public function getMaxRetries()
    {
        return $this->max_retries;
    }

    /**
     * Generated from protobuf field <code>int32 max_retries = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setMaxRetries($var)
    {
        GPBUtil::checkInt32($var);
        $this->max_retries = $var;

        return $this;
    }

}

