<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/compute/v1/compute.proto

namespace Google\Cloud\Compute\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>google.cloud.compute.v1.DiskInstantiationConfig</code>
 */
class DiskInstantiationConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool auto_delete = 1;</code>
     */
    protected $auto_delete = false;
    /**
     * Generated from protobuf field <code>string custom_image = 2;</code>
     */
    protected $custom_image = '';
    /**
     * Generated from protobuf field <code>string device_name = 3;</code>
     */
    protected $device_name = '';
    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.DiskInstantiationConfig.InstantiateFrom instantiate_from = 4;</code>
     */
    protected $instantiate_from = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $auto_delete
     *     @type string $custom_image
     *     @type string $device_name
     *     @type int $instantiate_from
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Cloud\Compute\V1\Compute::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool auto_delete = 1;</code>
     * @return bool
     */
    public function getAutoDelete()
    {
        return $this->auto_delete;
    }

    /**
     * Generated from protobuf field <code>bool auto_delete = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setAutoDelete($var)
    {
        GPBUtil::checkBool($var);
        $this->auto_delete = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string custom_image = 2;</code>
     * @return string
     */
    public function getCustomImage()
    {
        return $this->custom_image;
    }

    /**
     * Generated from protobuf field <code>string custom_image = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCustomImage($var)
    {
        GPBUtil::checkString($var, True);
        $this->custom_image = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string device_name = 3;</code>
     * @return string
     */
    public function getDeviceName()
    {
        return $this->device_name;
    }

    /**
     * Generated from protobuf field <code>string device_name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDeviceName($var)
    {
        GPBUtil::checkString($var, True);
        $this->device_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.DiskInstantiationConfig.InstantiateFrom instantiate_from = 4;</code>
     * @return int
     */
    public function getInstantiateFrom()
    {
        return $this->instantiate_from;
    }

    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.DiskInstantiationConfig.InstantiateFrom instantiate_from = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setInstantiateFrom($var)
    {
        GPBUtil::checkEnum($var, \Google\Cloud\Compute\V1\DiskInstantiationConfig_InstantiateFrom::class);
        $this->instantiate_from = $var;

        return $this;
    }

}

