<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/compute/v1/compute.proto

namespace Google\Cloud\Compute\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>google.cloud.compute.v1.DiskMoveRequest</code>
 */
class DiskMoveRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string destination_zone = 1;</code>
     */
    protected $destination_zone = '';
    /**
     * Generated from protobuf field <code>string target_disk = 2;</code>
     */
    protected $target_disk = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $destination_zone
     *     @type string $target_disk
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Cloud\Compute\V1\Compute::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string destination_zone = 1;</code>
     * @return string
     */
    public function getDestinationZone()
    {
        return $this->destination_zone;
    }

    /**
     * Generated from protobuf field <code>string destination_zone = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setDestinationZone($var)
    {
        GPBUtil::checkString($var, True);
        $this->destination_zone = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string target_disk = 2;</code>
     * @return string
     */
    public function getTargetDisk()
    {
        return $this->target_disk;
    }

    /**
     * Generated from protobuf field <code>string target_disk = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTargetDisk($var)
    {
        GPBUtil::checkString($var, True);
        $this->target_disk = $var;

        return $this;
    }

}

