<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/compute/v1/compute.proto

namespace Google\Cloud\Compute\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>google.cloud.compute.v1.GetBackendBucketRequest</code>
 */
class GetBackendBucketRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string backend_bucket = 1;</code>
     */
    protected $backend_bucket = '';
    /**
     * Generated from protobuf field <code>string project = 2;</code>
     */
    protected $project = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $backend_bucket
     *     @type string $project
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Cloud\Compute\V1\Compute::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string backend_bucket = 1;</code>
     * @return string
     */
    public function getBackendBucket()
    {
        return $this->backend_bucket;
    }

    /**
     * Generated from protobuf field <code>string backend_bucket = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setBackendBucket($var)
    {
        GPBUtil::checkString($var, True);
        $this->backend_bucket = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string project = 2;</code>
     * @return string
     */
    public function getProject()
    {
        return $this->project;
    }

    /**
     * Generated from protobuf field <code>string project = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setProject($var)
    {
        GPBUtil::checkString($var, True);
        $this->project = $var;

        return $this;
    }

}

