<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/compute/v1/compute.proto

namespace Google\Cloud\Compute\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>google.cloud.compute.v1.HttpRouteAction</code>
 */
class HttpRouteAction extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.CorsPolicy cors_policy = 1;</code>
     */
    protected $cors_policy = null;
    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.HttpFaultInjection fault_injection_policy = 2;</code>
     */
    protected $fault_injection_policy = null;
    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.RequestMirrorPolicy request_mirror_policy = 3;</code>
     */
    protected $request_mirror_policy = null;
    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.HttpRetryPolicy retry_policy = 4;</code>
     */
    protected $retry_policy = null;
    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.Duration timeout = 5;</code>
     */
    protected $timeout = null;
    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.UrlRewrite url_rewrite = 6;</code>
     */
    protected $url_rewrite = null;
    /**
     * Generated from protobuf field <code>repeated .google.cloud.compute.v1.WeightedBackendService weighted_backend_services = 7;</code>
     */
    private $weighted_backend_services;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Cloud\Compute\V1\CorsPolicy $cors_policy
     *     @type \Google\Cloud\Compute\V1\HttpFaultInjection $fault_injection_policy
     *     @type \Google\Cloud\Compute\V1\RequestMirrorPolicy $request_mirror_policy
     *     @type \Google\Cloud\Compute\V1\HttpRetryPolicy $retry_policy
     *     @type \Google\Cloud\Compute\V1\Duration $timeout
     *     @type \Google\Cloud\Compute\V1\UrlRewrite $url_rewrite
     *     @type \Google\Cloud\Compute\V1\WeightedBackendService[]|\Google\Protobuf\Internal\RepeatedField $weighted_backend_services
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Cloud\Compute\V1\Compute::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.CorsPolicy cors_policy = 1;</code>
     * @return \Google\Cloud\Compute\V1\CorsPolicy
     */
    public function getCorsPolicy()
    {
        return $this->cors_policy;
    }

    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.CorsPolicy cors_policy = 1;</code>
     * @param \Google\Cloud\Compute\V1\CorsPolicy $var
     * @return $this
     */
    public function setCorsPolicy($var)
    {
        GPBUtil::checkMessage($var, \Google\Cloud\Compute\V1\CorsPolicy::class);
        $this->cors_policy = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.HttpFaultInjection fault_injection_policy = 2;</code>
     * @return \Google\Cloud\Compute\V1\HttpFaultInjection
     */
    public function getFaultInjectionPolicy()
    {
        return $this->fault_injection_policy;
    }

    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.HttpFaultInjection fault_injection_policy = 2;</code>
     * @param \Google\Cloud\Compute\V1\HttpFaultInjection $var
     * @return $this
     */
    public function setFaultInjectionPolicy($var)
    {
        GPBUtil::checkMessage($var, \Google\Cloud\Compute\V1\HttpFaultInjection::class);
        $this->fault_injection_policy = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.RequestMirrorPolicy request_mirror_policy = 3;</code>
     * @return \Google\Cloud\Compute\V1\RequestMirrorPolicy
     */
    public function getRequestMirrorPolicy()
    {
        return $this->request_mirror_policy;
    }

    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.RequestMirrorPolicy request_mirror_policy = 3;</code>
     * @param \Google\Cloud\Compute\V1\RequestMirrorPolicy $var
     * @return $this
     */
    public function setRequestMirrorPolicy($var)
    {
        GPBUtil::checkMessage($var, \Google\Cloud\Compute\V1\RequestMirrorPolicy::class);
        $this->request_mirror_policy = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.HttpRetryPolicy retry_policy = 4;</code>
     * @return \Google\Cloud\Compute\V1\HttpRetryPolicy
     */
    public function getRetryPolicy()
    {
        return $this->retry_policy;
    }

    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.HttpRetryPolicy retry_policy = 4;</code>
     * @param \Google\Cloud\Compute\V1\HttpRetryPolicy $var
     * @return $this
     */
    public function setRetryPolicy($var)
    {
        GPBUtil::checkMessage($var, \Google\Cloud\Compute\V1\HttpRetryPolicy::class);
        $this->retry_policy = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.Duration timeout = 5;</code>
     * @return \Google\Cloud\Compute\V1\Duration
     */
    public function getTimeout()
    {
        return $this->timeout;
    }

    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.Duration timeout = 5;</code>
     * @param \Google\Cloud\Compute\V1\Duration $var
     * @return $this
     */
    public function setTimeout($var)
    {
        GPBUtil::checkMessage($var, \Google\Cloud\Compute\V1\Duration::class);
        $this->timeout = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.UrlRewrite url_rewrite = 6;</code>
     * @return \Google\Cloud\Compute\V1\UrlRewrite
     */
    public function getUrlRewrite()
    {
        return $this->url_rewrite;
    }

    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.UrlRewrite url_rewrite = 6;</code>
     * @param \Google\Cloud\Compute\V1\UrlRewrite $var
     * @return $this
     */
    public function setUrlRewrite($var)
    {
        GPBUtil::checkMessage($var, \Google\Cloud\Compute\V1\UrlRewrite::class);
        $this->url_rewrite = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .google.cloud.compute.v1.WeightedBackendService weighted_backend_services = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getWeightedBackendServices()
    {
        return $this->weighted_backend_services;
    }

    /**
     * Generated from protobuf field <code>repeated .google.cloud.compute.v1.WeightedBackendService weighted_backend_services = 7;</code>
     * @param \Google\Cloud\Compute\V1\WeightedBackendService[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setWeightedBackendServices($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Cloud\Compute\V1\WeightedBackendService::class);
        $this->weighted_backend_services = $arr;

        return $this;
    }

}

