<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/compute/v1/compute.proto

namespace Google\Cloud\Compute\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>google.cloud.compute.v1.InstanceGroupManagerStatus</code>
 */
class InstanceGroupManagerStatus extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string autoscaler = 1;</code>
     */
    protected $autoscaler = '';
    /**
     * Generated from protobuf field <code>bool is_stable = 2;</code>
     */
    protected $is_stable = false;
    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.InstanceGroupManagerStatusVersionTarget version_target = 3;</code>
     */
    protected $version_target = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $autoscaler
     *     @type bool $is_stable
     *     @type \Google\Cloud\Compute\V1\InstanceGroupManagerStatusVersionTarget $version_target
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Cloud\Compute\V1\Compute::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string autoscaler = 1;</code>
     * @return string
     */
    public function getAutoscaler()
    {
        return $this->autoscaler;
    }

    /**
     * Generated from protobuf field <code>string autoscaler = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAutoscaler($var)
    {
        GPBUtil::checkString($var, True);
        $this->autoscaler = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_stable = 2;</code>
     * @return bool
     */
    public function getIsStable()
    {
        return $this->is_stable;
    }

    /**
     * Generated from protobuf field <code>bool is_stable = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsStable($var)
    {
        GPBUtil::checkBool($var);
        $this->is_stable = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.InstanceGroupManagerStatusVersionTarget version_target = 3;</code>
     * @return \Google\Cloud\Compute\V1\InstanceGroupManagerStatusVersionTarget
     */
    public function getVersionTarget()
    {
        return $this->version_target;
    }

    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.InstanceGroupManagerStatusVersionTarget version_target = 3;</code>
     * @param \Google\Cloud\Compute\V1\InstanceGroupManagerStatusVersionTarget $var
     * @return $this
     */
    public function setVersionTarget($var)
    {
        GPBUtil::checkMessage($var, \Google\Cloud\Compute\V1\InstanceGroupManagerStatusVersionTarget::class);
        $this->version_target = $var;

        return $this;
    }

}

