<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/compute/v1/compute.proto

namespace Google\Cloud\Compute\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>google.cloud.compute.v1.InterconnectDiagnosticsLinkStatus</code>
 */
class InterconnectDiagnosticsLinkStatus extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .google.cloud.compute.v1.InterconnectDiagnosticsARPEntry arp_caches = 1;</code>
     */
    private $arp_caches;
    /**
     * Generated from protobuf field <code>string circuit_id = 2;</code>
     */
    protected $circuit_id = '';
    /**
     * Generated from protobuf field <code>string google_demarc = 3;</code>
     */
    protected $google_demarc = '';
    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.InterconnectDiagnosticsLinkLACPStatus lacp_status = 4;</code>
     */
    protected $lacp_status = null;
    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.InterconnectDiagnosticsLinkOpticalPower receiving_optical_power = 5;</code>
     */
    protected $receiving_optical_power = null;
    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.InterconnectDiagnosticsLinkOpticalPower transmitting_optical_power = 6;</code>
     */
    protected $transmitting_optical_power = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Cloud\Compute\V1\InterconnectDiagnosticsARPEntry[]|\Google\Protobuf\Internal\RepeatedField $arp_caches
     *     @type string $circuit_id
     *     @type string $google_demarc
     *     @type \Google\Cloud\Compute\V1\InterconnectDiagnosticsLinkLACPStatus $lacp_status
     *     @type \Google\Cloud\Compute\V1\InterconnectDiagnosticsLinkOpticalPower $receiving_optical_power
     *     @type \Google\Cloud\Compute\V1\InterconnectDiagnosticsLinkOpticalPower $transmitting_optical_power
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Cloud\Compute\V1\Compute::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .google.cloud.compute.v1.InterconnectDiagnosticsARPEntry arp_caches = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getArpCaches()
    {
        return $this->arp_caches;
    }

    /**
     * Generated from protobuf field <code>repeated .google.cloud.compute.v1.InterconnectDiagnosticsARPEntry arp_caches = 1;</code>
     * @param \Google\Cloud\Compute\V1\InterconnectDiagnosticsARPEntry[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setArpCaches($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Cloud\Compute\V1\InterconnectDiagnosticsARPEntry::class);
        $this->arp_caches = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string circuit_id = 2;</code>
     * @return string
     */
    public function getCircuitId()
    {
        return $this->circuit_id;
    }

    /**
     * Generated from protobuf field <code>string circuit_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCircuitId($var)
    {
        GPBUtil::checkString($var, True);
        $this->circuit_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string google_demarc = 3;</code>
     * @return string
     */
    public function getGoogleDemarc()
    {
        return $this->google_demarc;
    }

    /**
     * Generated from protobuf field <code>string google_demarc = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setGoogleDemarc($var)
    {
        GPBUtil::checkString($var, True);
        $this->google_demarc = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.InterconnectDiagnosticsLinkLACPStatus lacp_status = 4;</code>
     * @return \Google\Cloud\Compute\V1\InterconnectDiagnosticsLinkLACPStatus
     */
    public function getLacpStatus()
    {
        return $this->lacp_status;
    }

    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.InterconnectDiagnosticsLinkLACPStatus lacp_status = 4;</code>
     * @param \Google\Cloud\Compute\V1\InterconnectDiagnosticsLinkLACPStatus $var
     * @return $this
     */
    public function setLacpStatus($var)
    {
        GPBUtil::checkMessage($var, \Google\Cloud\Compute\V1\InterconnectDiagnosticsLinkLACPStatus::class);
        $this->lacp_status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.InterconnectDiagnosticsLinkOpticalPower receiving_optical_power = 5;</code>
     * @return \Google\Cloud\Compute\V1\InterconnectDiagnosticsLinkOpticalPower
     */
    public function getReceivingOpticalPower()
    {
        return $this->receiving_optical_power;
    }

    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.InterconnectDiagnosticsLinkOpticalPower receiving_optical_power = 5;</code>
     * @param \Google\Cloud\Compute\V1\InterconnectDiagnosticsLinkOpticalPower $var
     * @return $this
     */
    public function setReceivingOpticalPower($var)
    {
        GPBUtil::checkMessage($var, \Google\Cloud\Compute\V1\InterconnectDiagnosticsLinkOpticalPower::class);
        $this->receiving_optical_power = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.InterconnectDiagnosticsLinkOpticalPower transmitting_optical_power = 6;</code>
     * @return \Google\Cloud\Compute\V1\InterconnectDiagnosticsLinkOpticalPower
     */
    public function getTransmittingOpticalPower()
    {
        return $this->transmitting_optical_power;
    }

    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.InterconnectDiagnosticsLinkOpticalPower transmitting_optical_power = 6;</code>
     * @param \Google\Cloud\Compute\V1\InterconnectDiagnosticsLinkOpticalPower $var
     * @return $this
     */
    public function setTransmittingOpticalPower($var)
    {
        GPBUtil::checkMessage($var, \Google\Cloud\Compute\V1\InterconnectDiagnosticsLinkOpticalPower::class);
        $this->transmitting_optical_power = $var;

        return $this;
    }

}

