<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/compute/v1/compute.proto

namespace Google\Cloud\Compute\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>google.cloud.compute.v1.LogConfigCounterOptions</code>
 */
class LogConfigCounterOptions extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .google.cloud.compute.v1.LogConfigCounterOptionsCustomField custom_fields = 1;</code>
     */
    private $custom_fields;
    /**
     * Generated from protobuf field <code>string field = 2;</code>
     */
    protected $field = '';
    /**
     * Generated from protobuf field <code>string metric = 3;</code>
     */
    protected $metric = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Cloud\Compute\V1\LogConfigCounterOptionsCustomField[]|\Google\Protobuf\Internal\RepeatedField $custom_fields
     *     @type string $field
     *     @type string $metric
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Cloud\Compute\V1\Compute::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .google.cloud.compute.v1.LogConfigCounterOptionsCustomField custom_fields = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCustomFields()
    {
        return $this->custom_fields;
    }

    /**
     * Generated from protobuf field <code>repeated .google.cloud.compute.v1.LogConfigCounterOptionsCustomField custom_fields = 1;</code>
     * @param \Google\Cloud\Compute\V1\LogConfigCounterOptionsCustomField[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCustomFields($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Cloud\Compute\V1\LogConfigCounterOptionsCustomField::class);
        $this->custom_fields = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string field = 2;</code>
     * @return string
     */
    public function getField()
    {
        return $this->field;
    }

    /**
     * Generated from protobuf field <code>string field = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setField($var)
    {
        GPBUtil::checkString($var, True);
        $this->field = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string metric = 3;</code>
     * @return string
     */
    public function getMetric()
    {
        return $this->metric;
    }

    /**
     * Generated from protobuf field <code>string metric = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setMetric($var)
    {
        GPBUtil::checkString($var, True);
        $this->metric = $var;

        return $this;
    }

}

