<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/compute/v1/compute.proto

namespace Google\Cloud\Compute\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>google.cloud.compute.v1.ManagedInstanceLastAttempt</code>
 */
class ManagedInstanceLastAttempt extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.Errors errors = 1;</code>
     */
    protected $errors = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Cloud\Compute\V1\Errors $errors
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Cloud\Compute\V1\Compute::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.Errors errors = 1;</code>
     * @return \Google\Cloud\Compute\V1\Errors
     */
    public function getErrors()
    {
        return $this->errors;
    }

    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.Errors errors = 1;</code>
     * @param \Google\Cloud\Compute\V1\Errors $var
     * @return $this
     */
    public function setErrors($var)
    {
        GPBUtil::checkMessage($var, \Google\Cloud\Compute\V1\Errors::class);
        $this->errors = $var;

        return $this;
    }

}

