<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/compute/v1/compute.proto

namespace Google\Cloud\Compute\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>google.cloud.compute.v1.NetworkPeering</code>
 */
class NetworkPeering extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool auto_create_routes = 1;</code>
     */
    protected $auto_create_routes = false;
    /**
     * Generated from protobuf field <code>bool exchange_subnet_routes = 2;</code>
     */
    protected $exchange_subnet_routes = false;
    /**
     * Generated from protobuf field <code>bool export_custom_routes = 3;</code>
     */
    protected $export_custom_routes = false;
    /**
     * Generated from protobuf field <code>bool import_custom_routes = 4;</code>
     */
    protected $import_custom_routes = false;
    /**
     * Generated from protobuf field <code>string name = 5;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>string network = 6;</code>
     */
    protected $network = '';
    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.NetworkPeering.State state = 7;</code>
     */
    protected $state = 0;
    /**
     * Generated from protobuf field <code>string state_details = 8;</code>
     */
    protected $state_details = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $auto_create_routes
     *     @type bool $exchange_subnet_routes
     *     @type bool $export_custom_routes
     *     @type bool $import_custom_routes
     *     @type string $name
     *     @type string $network
     *     @type int $state
     *     @type string $state_details
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Cloud\Compute\V1\Compute::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool auto_create_routes = 1;</code>
     * @return bool
     */
    public function getAutoCreateRoutes()
    {
        return $this->auto_create_routes;
    }

    /**
     * Generated from protobuf field <code>bool auto_create_routes = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setAutoCreateRoutes($var)
    {
        GPBUtil::checkBool($var);
        $this->auto_create_routes = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool exchange_subnet_routes = 2;</code>
     * @return bool
     */
    public function getExchangeSubnetRoutes()
    {
        return $this->exchange_subnet_routes;
    }

    /**
     * Generated from protobuf field <code>bool exchange_subnet_routes = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setExchangeSubnetRoutes($var)
    {
        GPBUtil::checkBool($var);
        $this->exchange_subnet_routes = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool export_custom_routes = 3;</code>
     * @return bool
     */
    public function getExportCustomRoutes()
    {
        return $this->export_custom_routes;
    }

    /**
     * Generated from protobuf field <code>bool export_custom_routes = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setExportCustomRoutes($var)
    {
        GPBUtil::checkBool($var);
        $this->export_custom_routes = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool import_custom_routes = 4;</code>
     * @return bool
     */
    public function getImportCustomRoutes()
    {
        return $this->import_custom_routes;
    }

    /**
     * Generated from protobuf field <code>bool import_custom_routes = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setImportCustomRoutes($var)
    {
        GPBUtil::checkBool($var);
        $this->import_custom_routes = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 5;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string network = 6;</code>
     * @return string
     */
    public function getNetwork()
    {
        return $this->network;
    }

    /**
     * Generated from protobuf field <code>string network = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setNetwork($var)
    {
        GPBUtil::checkString($var, True);
        $this->network = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.NetworkPeering.State state = 7;</code>
     * @return int
     */
    public function getState()
    {
        return $this->state;
    }

    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.NetworkPeering.State state = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setState($var)
    {
        GPBUtil::checkEnum($var, \Google\Cloud\Compute\V1\NetworkPeering_State::class);
        $this->state = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string state_details = 8;</code>
     * @return string
     */
    public function getStateDetails()
    {
        return $this->state_details;
    }

    /**
     * Generated from protobuf field <code>string state_details = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setStateDetails($var)
    {
        GPBUtil::checkString($var, True);
        $this->state_details = $var;

        return $this;
    }

}

