<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/compute/v1/compute.proto

namespace Google\Cloud\Compute\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>google.cloud.compute.v1.OutlierDetection</code>
 */
class OutlierDetection extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.Duration base_ejection_time = 1;</code>
     */
    protected $base_ejection_time = null;
    /**
     * Generated from protobuf field <code>int32 consecutive_errors = 2;</code>
     */
    protected $consecutive_errors = 0;
    /**
     * Generated from protobuf field <code>int32 consecutive_gateway_failure = 3;</code>
     */
    protected $consecutive_gateway_failure = 0;
    /**
     * Generated from protobuf field <code>int32 enforcing_consecutive_errors = 4;</code>
     */
    protected $enforcing_consecutive_errors = 0;
    /**
     * Generated from protobuf field <code>int32 enforcing_consecutive_gateway_failure = 5;</code>
     */
    protected $enforcing_consecutive_gateway_failure = 0;
    /**
     * Generated from protobuf field <code>int32 enforcing_success_rate = 6;</code>
     */
    protected $enforcing_success_rate = 0;
    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.Duration interval = 7;</code>
     */
    protected $interval = null;
    /**
     * Generated from protobuf field <code>int32 max_ejection_percent = 8;</code>
     */
    protected $max_ejection_percent = 0;
    /**
     * Generated from protobuf field <code>int32 success_rate_minimum_hosts = 9;</code>
     */
    protected $success_rate_minimum_hosts = 0;
    /**
     * Generated from protobuf field <code>int32 success_rate_request_volume = 10;</code>
     */
    protected $success_rate_request_volume = 0;
    /**
     * Generated from protobuf field <code>int32 success_rate_stdev_factor = 11;</code>
     */
    protected $success_rate_stdev_factor = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Cloud\Compute\V1\Duration $base_ejection_time
     *     @type int $consecutive_errors
     *     @type int $consecutive_gateway_failure
     *     @type int $enforcing_consecutive_errors
     *     @type int $enforcing_consecutive_gateway_failure
     *     @type int $enforcing_success_rate
     *     @type \Google\Cloud\Compute\V1\Duration $interval
     *     @type int $max_ejection_percent
     *     @type int $success_rate_minimum_hosts
     *     @type int $success_rate_request_volume
     *     @type int $success_rate_stdev_factor
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Cloud\Compute\V1\Compute::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.Duration base_ejection_time = 1;</code>
     * @return \Google\Cloud\Compute\V1\Duration
     */
    public function getBaseEjectionTime()
    {
        return $this->base_ejection_time;
    }

    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.Duration base_ejection_time = 1;</code>
     * @param \Google\Cloud\Compute\V1\Duration $var
     * @return $this
     */
    public function setBaseEjectionTime($var)
    {
        GPBUtil::checkMessage($var, \Google\Cloud\Compute\V1\Duration::class);
        $this->base_ejection_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 consecutive_errors = 2;</code>
     * @return int
     */
    public function getConsecutiveErrors()
    {
        return $this->consecutive_errors;
    }

    /**
     * Generated from protobuf field <code>int32 consecutive_errors = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setConsecutiveErrors($var)
    {
        GPBUtil::checkInt32($var);
        $this->consecutive_errors = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 consecutive_gateway_failure = 3;</code>
     * @return int
     */
    public function getConsecutiveGatewayFailure()
    {
        return $this->consecutive_gateway_failure;
    }

    /**
     * Generated from protobuf field <code>int32 consecutive_gateway_failure = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setConsecutiveGatewayFailure($var)
    {
        GPBUtil::checkInt32($var);
        $this->consecutive_gateway_failure = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 enforcing_consecutive_errors = 4;</code>
     * @return int
     */
    public function getEnforcingConsecutiveErrors()
    {
        return $this->enforcing_consecutive_errors;
    }

    /**
     * Generated from protobuf field <code>int32 enforcing_consecutive_errors = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setEnforcingConsecutiveErrors($var)
    {
        GPBUtil::checkInt32($var);
        $this->enforcing_consecutive_errors = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 enforcing_consecutive_gateway_failure = 5;</code>
     * @return int
     */
    public function getEnforcingConsecutiveGatewayFailure()
    {
        return $this->enforcing_consecutive_gateway_failure;
    }

    /**
     * Generated from protobuf field <code>int32 enforcing_consecutive_gateway_failure = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setEnforcingConsecutiveGatewayFailure($var)
    {
        GPBUtil::checkInt32($var);
        $this->enforcing_consecutive_gateway_failure = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 enforcing_success_rate = 6;</code>
     * @return int
     */
    public function getEnforcingSuccessRate()
    {
        return $this->enforcing_success_rate;
    }

    /**
     * Generated from protobuf field <code>int32 enforcing_success_rate = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setEnforcingSuccessRate($var)
    {
        GPBUtil::checkInt32($var);
        $this->enforcing_success_rate = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.Duration interval = 7;</code>
     * @return \Google\Cloud\Compute\V1\Duration
     */
    public function getInterval()
    {
        return $this->interval;
    }

    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.Duration interval = 7;</code>
     * @param \Google\Cloud\Compute\V1\Duration $var
     * @return $this
     */
    public function setInterval($var)
    {
        GPBUtil::checkMessage($var, \Google\Cloud\Compute\V1\Duration::class);
        $this->interval = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 max_ejection_percent = 8;</code>
     * @return int
     */
    public function getMaxEjectionPercent()
    {
        return $this->max_ejection_percent;
    }

    /**
     * Generated from protobuf field <code>int32 max_ejection_percent = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setMaxEjectionPercent($var)
    {
        GPBUtil::checkInt32($var);
        $this->max_ejection_percent = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 success_rate_minimum_hosts = 9;</code>
     * @return int
     */
    public function getSuccessRateMinimumHosts()
    {
        return $this->success_rate_minimum_hosts;
    }

    /**
     * Generated from protobuf field <code>int32 success_rate_minimum_hosts = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setSuccessRateMinimumHosts($var)
    {
        GPBUtil::checkInt32($var);
        $this->success_rate_minimum_hosts = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 success_rate_request_volume = 10;</code>
     * @return int
     */
    public function getSuccessRateRequestVolume()
    {
        return $this->success_rate_request_volume;
    }

    /**
     * Generated from protobuf field <code>int32 success_rate_request_volume = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setSuccessRateRequestVolume($var)
    {
        GPBUtil::checkInt32($var);
        $this->success_rate_request_volume = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 success_rate_stdev_factor = 11;</code>
     * @return int
     */
    public function getSuccessRateStdevFactor()
    {
        return $this->success_rate_stdev_factor;
    }

    /**
     * Generated from protobuf field <code>int32 success_rate_stdev_factor = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setSuccessRateStdevFactor($var)
    {
        GPBUtil::checkInt32($var);
        $this->success_rate_stdev_factor = $var;

        return $this;
    }

}

