<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/compute/v1/compute.proto

namespace Google\Cloud\Compute\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>google.cloud.compute.v1.PatchHttpsHealthCheckRequest</code>
 */
class PatchHttpsHealthCheckRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string https_health_check = 1;</code>
     */
    protected $https_health_check = '';
    /**
     * Generated from protobuf field <code>string project = 2;</code>
     */
    protected $project = '';
    /**
     * Generated from protobuf field <code>string request_id = 3;</code>
     */
    protected $request_id = '';
    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.HttpsHealthCheck https_health_check_resource = 4;</code>
     */
    protected $https_health_check_resource = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $https_health_check
     *     @type string $project
     *     @type string $request_id
     *     @type \Google\Cloud\Compute\V1\HttpsHealthCheck $https_health_check_resource
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Cloud\Compute\V1\Compute::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string https_health_check = 1;</code>
     * @return string
     */
    public function getHttpsHealthCheck()
    {
        return $this->https_health_check;
    }

    /**
     * Generated from protobuf field <code>string https_health_check = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setHttpsHealthCheck($var)
    {
        GPBUtil::checkString($var, True);
        $this->https_health_check = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string project = 2;</code>
     * @return string
     */
    public function getProject()
    {
        return $this->project;
    }

    /**
     * Generated from protobuf field <code>string project = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setProject($var)
    {
        GPBUtil::checkString($var, True);
        $this->project = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string request_id = 3;</code>
     * @return string
     */
    public function getRequestId()
    {
        return $this->request_id;
    }

    /**
     * Generated from protobuf field <code>string request_id = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setRequestId($var)
    {
        GPBUtil::checkString($var, True);
        $this->request_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.HttpsHealthCheck https_health_check_resource = 4;</code>
     * @return \Google\Cloud\Compute\V1\HttpsHealthCheck
     */
    public function getHttpsHealthCheckResource()
    {
        return $this->https_health_check_resource;
    }

    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.HttpsHealthCheck https_health_check_resource = 4;</code>
     * @param \Google\Cloud\Compute\V1\HttpsHealthCheck $var
     * @return $this
     */
    public function setHttpsHealthCheckResource($var)
    {
        GPBUtil::checkMessage($var, \Google\Cloud\Compute\V1\HttpsHealthCheck::class);
        $this->https_health_check_resource = $var;

        return $this;
    }

}

