<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/compute/v1/compute.proto

namespace Google\Cloud\Compute\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>google.cloud.compute.v1.Router</code>
 */
class Router extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.RouterBgp bgp = 1;</code>
     */
    protected $bgp = null;
    /**
     * Generated from protobuf field <code>repeated .google.cloud.compute.v1.RouterBgpPeer bgp_peers = 2;</code>
     */
    private $bgp_peers;
    /**
     * Generated from protobuf field <code>string creation_timestamp = 3;</code>
     */
    protected $creation_timestamp = '';
    /**
     * Generated from protobuf field <code>string description = 4;</code>
     */
    protected $description = '';
    /**
     * Generated from protobuf field <code>string id = 5;</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>repeated .google.cloud.compute.v1.RouterInterface interfaces = 6;</code>
     */
    private $interfaces;
    /**
     * Generated from protobuf field <code>string kind = 7;</code>
     */
    protected $kind = '';
    /**
     * Generated from protobuf field <code>string name = 8;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>repeated .google.cloud.compute.v1.RouterNat nats = 9;</code>
     */
    private $nats;
    /**
     * Generated from protobuf field <code>string network = 10;</code>
     */
    protected $network = '';
    /**
     * Generated from protobuf field <code>string region = 11;</code>
     */
    protected $region = '';
    /**
     * Generated from protobuf field <code>string self_link = 12;</code>
     */
    protected $self_link = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Cloud\Compute\V1\RouterBgp $bgp
     *     @type \Google\Cloud\Compute\V1\RouterBgpPeer[]|\Google\Protobuf\Internal\RepeatedField $bgp_peers
     *     @type string $creation_timestamp
     *     @type string $description
     *     @type string $id
     *     @type \Google\Cloud\Compute\V1\RouterInterface[]|\Google\Protobuf\Internal\RepeatedField $interfaces
     *     @type string $kind
     *     @type string $name
     *     @type \Google\Cloud\Compute\V1\RouterNat[]|\Google\Protobuf\Internal\RepeatedField $nats
     *     @type string $network
     *     @type string $region
     *     @type string $self_link
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Cloud\Compute\V1\Compute::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.RouterBgp bgp = 1;</code>
     * @return \Google\Cloud\Compute\V1\RouterBgp
     */
    public function getBgp()
    {
        return $this->bgp;
    }

    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.RouterBgp bgp = 1;</code>
     * @param \Google\Cloud\Compute\V1\RouterBgp $var
     * @return $this
     */
    public function setBgp($var)
    {
        GPBUtil::checkMessage($var, \Google\Cloud\Compute\V1\RouterBgp::class);
        $this->bgp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .google.cloud.compute.v1.RouterBgpPeer bgp_peers = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getBgpPeers()
    {
        return $this->bgp_peers;
    }

    /**
     * Generated from protobuf field <code>repeated .google.cloud.compute.v1.RouterBgpPeer bgp_peers = 2;</code>
     * @param \Google\Cloud\Compute\V1\RouterBgpPeer[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setBgpPeers($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Cloud\Compute\V1\RouterBgpPeer::class);
        $this->bgp_peers = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string creation_timestamp = 3;</code>
     * @return string
     */
    public function getCreationTimestamp()
    {
        return $this->creation_timestamp;
    }

    /**
     * Generated from protobuf field <code>string creation_timestamp = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCreationTimestamp($var)
    {
        GPBUtil::checkString($var, True);
        $this->creation_timestamp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string description = 4;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>string description = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string id = 5;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .google.cloud.compute.v1.RouterInterface interfaces = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getInterfaces()
    {
        return $this->interfaces;
    }

    /**
     * Generated from protobuf field <code>repeated .google.cloud.compute.v1.RouterInterface interfaces = 6;</code>
     * @param \Google\Cloud\Compute\V1\RouterInterface[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setInterfaces($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Cloud\Compute\V1\RouterInterface::class);
        $this->interfaces = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string kind = 7;</code>
     * @return string
     */
    public function getKind()
    {
        return $this->kind;
    }

    /**
     * Generated from protobuf field <code>string kind = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setKind($var)
    {
        GPBUtil::checkString($var, True);
        $this->kind = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 8;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .google.cloud.compute.v1.RouterNat nats = 9;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getNats()
    {
        return $this->nats;
    }

    /**
     * Generated from protobuf field <code>repeated .google.cloud.compute.v1.RouterNat nats = 9;</code>
     * @param \Google\Cloud\Compute\V1\RouterNat[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setNats($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Cloud\Compute\V1\RouterNat::class);
        $this->nats = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string network = 10;</code>
     * @return string
     */
    public function getNetwork()
    {
        return $this->network;
    }

    /**
     * Generated from protobuf field <code>string network = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setNetwork($var)
    {
        GPBUtil::checkString($var, True);
        $this->network = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string region = 11;</code>
     * @return string
     */
    public function getRegion()
    {
        return $this->region;
    }

    /**
     * Generated from protobuf field <code>string region = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setRegion($var)
    {
        GPBUtil::checkString($var, True);
        $this->region = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string self_link = 12;</code>
     * @return string
     */
    public function getSelfLink()
    {
        return $this->self_link;
    }

    /**
     * Generated from protobuf field <code>string self_link = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setSelfLink($var)
    {
        GPBUtil::checkString($var, True);
        $this->self_link = $var;

        return $this;
    }

}

