<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/compute/v1/compute.proto

namespace Google\Cloud\Compute\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>google.cloud.compute.v1.RouterNat</code>
 */
class RouterNat extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated string drain_nat_ips = 1;</code>
     */
    private $drain_nat_ips;
    /**
     * Generated from protobuf field <code>int32 icmp_idle_timeout_sec = 2;</code>
     */
    protected $icmp_idle_timeout_sec = 0;
    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.RouterNatLogConfig log_config = 3;</code>
     */
    protected $log_config = null;
    /**
     * Generated from protobuf field <code>int32 min_ports_per_vm = 4;</code>
     */
    protected $min_ports_per_vm = 0;
    /**
     * Generated from protobuf field <code>string name = 5;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.RouterNat.NatIpAllocateOption nat_ip_allocate_option = 6;</code>
     */
    protected $nat_ip_allocate_option = 0;
    /**
     * Generated from protobuf field <code>repeated string nat_ips = 7;</code>
     */
    private $nat_ips;
    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.RouterNat.SourceSubnetworkIpRangesToNat source_subnetwork_ip_ranges_to_nat = 8;</code>
     */
    protected $source_subnetwork_ip_ranges_to_nat = 0;
    /**
     * Generated from protobuf field <code>repeated .google.cloud.compute.v1.RouterNatSubnetworkToNat subnetworks = 9;</code>
     */
    private $subnetworks;
    /**
     * Generated from protobuf field <code>int32 tcp_established_idle_timeout_sec = 10;</code>
     */
    protected $tcp_established_idle_timeout_sec = 0;
    /**
     * Generated from protobuf field <code>int32 tcp_transitory_idle_timeout_sec = 11;</code>
     */
    protected $tcp_transitory_idle_timeout_sec = 0;
    /**
     * Generated from protobuf field <code>int32 udp_idle_timeout_sec = 12;</code>
     */
    protected $udp_idle_timeout_sec = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $drain_nat_ips
     *     @type int $icmp_idle_timeout_sec
     *     @type \Google\Cloud\Compute\V1\RouterNatLogConfig $log_config
     *     @type int $min_ports_per_vm
     *     @type string $name
     *     @type int $nat_ip_allocate_option
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $nat_ips
     *     @type int $source_subnetwork_ip_ranges_to_nat
     *     @type \Google\Cloud\Compute\V1\RouterNatSubnetworkToNat[]|\Google\Protobuf\Internal\RepeatedField $subnetworks
     *     @type int $tcp_established_idle_timeout_sec
     *     @type int $tcp_transitory_idle_timeout_sec
     *     @type int $udp_idle_timeout_sec
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Cloud\Compute\V1\Compute::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated string drain_nat_ips = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDrainNatIps()
    {
        return $this->drain_nat_ips;
    }

    /**
     * Generated from protobuf field <code>repeated string drain_nat_ips = 1;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDrainNatIps($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->drain_nat_ips = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 icmp_idle_timeout_sec = 2;</code>
     * @return int
     */
    public function getIcmpIdleTimeoutSec()
    {
        return $this->icmp_idle_timeout_sec;
    }

    /**
     * Generated from protobuf field <code>int32 icmp_idle_timeout_sec = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setIcmpIdleTimeoutSec($var)
    {
        GPBUtil::checkInt32($var);
        $this->icmp_idle_timeout_sec = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.RouterNatLogConfig log_config = 3;</code>
     * @return \Google\Cloud\Compute\V1\RouterNatLogConfig
     */
    public function getLogConfig()
    {
        return $this->log_config;
    }

    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.RouterNatLogConfig log_config = 3;</code>
     * @param \Google\Cloud\Compute\V1\RouterNatLogConfig $var
     * @return $this
     */
    public function setLogConfig($var)
    {
        GPBUtil::checkMessage($var, \Google\Cloud\Compute\V1\RouterNatLogConfig::class);
        $this->log_config = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 min_ports_per_vm = 4;</code>
     * @return int
     */
    public function getMinPortsPerVm()
    {
        return $this->min_ports_per_vm;
    }

    /**
     * Generated from protobuf field <code>int32 min_ports_per_vm = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setMinPortsPerVm($var)
    {
        GPBUtil::checkInt32($var);
        $this->min_ports_per_vm = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 5;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.RouterNat.NatIpAllocateOption nat_ip_allocate_option = 6;</code>
     * @return int
     */
    public function getNatIpAllocateOption()
    {
        return $this->nat_ip_allocate_option;
    }

    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.RouterNat.NatIpAllocateOption nat_ip_allocate_option = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setNatIpAllocateOption($var)
    {
        GPBUtil::checkEnum($var, \Google\Cloud\Compute\V1\RouterNat_NatIpAllocateOption::class);
        $this->nat_ip_allocate_option = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string nat_ips = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getNatIps()
    {
        return $this->nat_ips;
    }

    /**
     * Generated from protobuf field <code>repeated string nat_ips = 7;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setNatIps($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->nat_ips = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.RouterNat.SourceSubnetworkIpRangesToNat source_subnetwork_ip_ranges_to_nat = 8;</code>
     * @return int
     */
    public function getSourceSubnetworkIpRangesToNat()
    {
        return $this->source_subnetwork_ip_ranges_to_nat;
    }

    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.RouterNat.SourceSubnetworkIpRangesToNat source_subnetwork_ip_ranges_to_nat = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setSourceSubnetworkIpRangesToNat($var)
    {
        GPBUtil::checkEnum($var, \Google\Cloud\Compute\V1\RouterNat_SourceSubnetworkIpRangesToNat::class);
        $this->source_subnetwork_ip_ranges_to_nat = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .google.cloud.compute.v1.RouterNatSubnetworkToNat subnetworks = 9;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSubnetworks()
    {
        return $this->subnetworks;
    }

    /**
     * Generated from protobuf field <code>repeated .google.cloud.compute.v1.RouterNatSubnetworkToNat subnetworks = 9;</code>
     * @param \Google\Cloud\Compute\V1\RouterNatSubnetworkToNat[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSubnetworks($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Cloud\Compute\V1\RouterNatSubnetworkToNat::class);
        $this->subnetworks = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 tcp_established_idle_timeout_sec = 10;</code>
     * @return int
     */
    public function getTcpEstablishedIdleTimeoutSec()
    {
        return $this->tcp_established_idle_timeout_sec;
    }

    /**
     * Generated from protobuf field <code>int32 tcp_established_idle_timeout_sec = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setTcpEstablishedIdleTimeoutSec($var)
    {
        GPBUtil::checkInt32($var);
        $this->tcp_established_idle_timeout_sec = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 tcp_transitory_idle_timeout_sec = 11;</code>
     * @return int
     */
    public function getTcpTransitoryIdleTimeoutSec()
    {
        return $this->tcp_transitory_idle_timeout_sec;
    }

    /**
     * Generated from protobuf field <code>int32 tcp_transitory_idle_timeout_sec = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setTcpTransitoryIdleTimeoutSec($var)
    {
        GPBUtil::checkInt32($var);
        $this->tcp_transitory_idle_timeout_sec = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 udp_idle_timeout_sec = 12;</code>
     * @return int
     */
    public function getUdpIdleTimeoutSec()
    {
        return $this->udp_idle_timeout_sec;
    }

    /**
     * Generated from protobuf field <code>int32 udp_idle_timeout_sec = 12;</code>
     * @param int $var
     * @return $this
     */
    public function setUdpIdleTimeoutSec($var)
    {
        GPBUtil::checkInt32($var);
        $this->udp_idle_timeout_sec = $var;

        return $this;
    }

}

