<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/compute/v1/compute.proto

namespace Google\Cloud\Compute\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>google.cloud.compute.v1.RouterStatusBgpPeerStatus</code>
 */
class RouterStatusBgpPeerStatus extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .google.cloud.compute.v1.Route advertised_routes = 1;</code>
     */
    private $advertised_routes;
    /**
     * Generated from protobuf field <code>string ip_address = 2;</code>
     */
    protected $ip_address = '';
    /**
     * Generated from protobuf field <code>string linked_vpn_tunnel = 3;</code>
     */
    protected $linked_vpn_tunnel = '';
    /**
     * Generated from protobuf field <code>string name = 4;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>uint32 num_learned_routes = 5;</code>
     */
    protected $num_learned_routes = 0;
    /**
     * Generated from protobuf field <code>string peer_ip_address = 6;</code>
     */
    protected $peer_ip_address = '';
    /**
     * Generated from protobuf field <code>string state = 7;</code>
     */
    protected $state = '';
    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.RouterStatusBgpPeerStatus.Status status = 8;</code>
     */
    protected $status = 0;
    /**
     * Generated from protobuf field <code>string uptime = 9;</code>
     */
    protected $uptime = '';
    /**
     * Generated from protobuf field <code>string uptime_seconds = 10;</code>
     */
    protected $uptime_seconds = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Cloud\Compute\V1\Route[]|\Google\Protobuf\Internal\RepeatedField $advertised_routes
     *     @type string $ip_address
     *     @type string $linked_vpn_tunnel
     *     @type string $name
     *     @type int $num_learned_routes
     *     @type string $peer_ip_address
     *     @type string $state
     *     @type int $status
     *     @type string $uptime
     *     @type string $uptime_seconds
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Cloud\Compute\V1\Compute::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .google.cloud.compute.v1.Route advertised_routes = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAdvertisedRoutes()
    {
        return $this->advertised_routes;
    }

    /**
     * Generated from protobuf field <code>repeated .google.cloud.compute.v1.Route advertised_routes = 1;</code>
     * @param \Google\Cloud\Compute\V1\Route[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAdvertisedRoutes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Cloud\Compute\V1\Route::class);
        $this->advertised_routes = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ip_address = 2;</code>
     * @return string
     */
    public function getIpAddress()
    {
        return $this->ip_address;
    }

    /**
     * Generated from protobuf field <code>string ip_address = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setIpAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->ip_address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string linked_vpn_tunnel = 3;</code>
     * @return string
     */
    public function getLinkedVpnTunnel()
    {
        return $this->linked_vpn_tunnel;
    }

    /**
     * Generated from protobuf field <code>string linked_vpn_tunnel = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setLinkedVpnTunnel($var)
    {
        GPBUtil::checkString($var, True);
        $this->linked_vpn_tunnel = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 4;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 num_learned_routes = 5;</code>
     * @return int
     */
    public function getNumLearnedRoutes()
    {
        return $this->num_learned_routes;
    }

    /**
     * Generated from protobuf field <code>uint32 num_learned_routes = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setNumLearnedRoutes($var)
    {
        GPBUtil::checkUint32($var);
        $this->num_learned_routes = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string peer_ip_address = 6;</code>
     * @return string
     */
    public function getPeerIpAddress()
    {
        return $this->peer_ip_address;
    }

    /**
     * Generated from protobuf field <code>string peer_ip_address = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setPeerIpAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->peer_ip_address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string state = 7;</code>
     * @return string
     */
    public function getState()
    {
        return $this->state;
    }

    /**
     * Generated from protobuf field <code>string state = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setState($var)
    {
        GPBUtil::checkString($var, True);
        $this->state = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.RouterStatusBgpPeerStatus.Status status = 8;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.RouterStatusBgpPeerStatus.Status status = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \Google\Cloud\Compute\V1\RouterStatusBgpPeerStatus_Status::class);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string uptime = 9;</code>
     * @return string
     */
    public function getUptime()
    {
        return $this->uptime;
    }

    /**
     * Generated from protobuf field <code>string uptime = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setUptime($var)
    {
        GPBUtil::checkString($var, True);
        $this->uptime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string uptime_seconds = 10;</code>
     * @return string
     */
    public function getUptimeSeconds()
    {
        return $this->uptime_seconds;
    }

    /**
     * Generated from protobuf field <code>string uptime_seconds = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setUptimeSeconds($var)
    {
        GPBUtil::checkString($var, True);
        $this->uptime_seconds = $var;

        return $this;
    }

}

