<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/compute/v1/compute.proto

namespace Google\Cloud\Compute\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>google.cloud.compute.v1.SignedUrlKey</code>
 */
class SignedUrlKey extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string key_name = 1;</code>
     */
    protected $key_name = '';
    /**
     * Generated from protobuf field <code>string key_value = 2;</code>
     */
    protected $key_value = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $key_name
     *     @type string $key_value
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Cloud\Compute\V1\Compute::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string key_name = 1;</code>
     * @return string
     */
    public function getKeyName()
    {
        return $this->key_name;
    }

    /**
     * Generated from protobuf field <code>string key_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setKeyName($var)
    {
        GPBUtil::checkString($var, True);
        $this->key_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string key_value = 2;</code>
     * @return string
     */
    public function getKeyValue()
    {
        return $this->key_value;
    }

    /**
     * Generated from protobuf field <code>string key_value = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setKeyValue($var)
    {
        GPBUtil::checkString($var, True);
        $this->key_value = $var;

        return $this;
    }

}

