<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/compute/v1/compute.proto

namespace Google\Cloud\Compute\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>google.cloud.compute.v1.Snapshot</code>
 */
class Snapshot extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool auto_created = 1;</code>
     */
    protected $auto_created = false;
    /**
     * Generated from protobuf field <code>string creation_timestamp = 2;</code>
     */
    protected $creation_timestamp = '';
    /**
     * Generated from protobuf field <code>string description = 3;</code>
     */
    protected $description = '';
    /**
     * Generated from protobuf field <code>string disk_size_gb = 4;</code>
     */
    protected $disk_size_gb = '';
    /**
     * Generated from protobuf field <code>string download_bytes = 5;</code>
     */
    protected $download_bytes = '';
    /**
     * Generated from protobuf field <code>string id = 6;</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>string kind = 7;</code>
     */
    protected $kind = '';
    /**
     * Generated from protobuf field <code>string label_fingerprint = 8;</code>
     */
    protected $label_fingerprint = '';
    /**
     * Generated from protobuf field <code>map<string, string> labels = 9;</code>
     */
    private $labels;
    /**
     * Generated from protobuf field <code>repeated string license_codes = 10;</code>
     */
    private $license_codes;
    /**
     * Generated from protobuf field <code>repeated string licenses = 11;</code>
     */
    private $licenses;
    /**
     * Generated from protobuf field <code>string name = 12;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>string self_link = 13;</code>
     */
    protected $self_link = '';
    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.CustomerEncryptionKey snapshot_encryption_key = 14;</code>
     */
    protected $snapshot_encryption_key = null;
    /**
     * Generated from protobuf field <code>string source_disk = 15;</code>
     */
    protected $source_disk = '';
    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.CustomerEncryptionKey source_disk_encryption_key = 16;</code>
     */
    protected $source_disk_encryption_key = null;
    /**
     * Generated from protobuf field <code>string source_disk_id = 17;</code>
     */
    protected $source_disk_id = '';
    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.Snapshot.Status status = 18;</code>
     */
    protected $status = 0;
    /**
     * Generated from protobuf field <code>string storage_bytes = 19;</code>
     */
    protected $storage_bytes = '';
    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.Snapshot.StorageBytesStatus storage_bytes_status = 20;</code>
     */
    protected $storage_bytes_status = 0;
    /**
     * Generated from protobuf field <code>repeated string storage_locations = 21;</code>
     */
    private $storage_locations;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $auto_created
     *     @type string $creation_timestamp
     *     @type string $description
     *     @type string $disk_size_gb
     *     @type string $download_bytes
     *     @type string $id
     *     @type string $kind
     *     @type string $label_fingerprint
     *     @type array|\Google\Protobuf\Internal\MapField $labels
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $license_codes
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $licenses
     *     @type string $name
     *     @type string $self_link
     *     @type \Google\Cloud\Compute\V1\CustomerEncryptionKey $snapshot_encryption_key
     *     @type string $source_disk
     *     @type \Google\Cloud\Compute\V1\CustomerEncryptionKey $source_disk_encryption_key
     *     @type string $source_disk_id
     *     @type int $status
     *     @type string $storage_bytes
     *     @type int $storage_bytes_status
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $storage_locations
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Cloud\Compute\V1\Compute::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool auto_created = 1;</code>
     * @return bool
     */
    public function getAutoCreated()
    {
        return $this->auto_created;
    }

    /**
     * Generated from protobuf field <code>bool auto_created = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setAutoCreated($var)
    {
        GPBUtil::checkBool($var);
        $this->auto_created = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string creation_timestamp = 2;</code>
     * @return string
     */
    public function getCreationTimestamp()
    {
        return $this->creation_timestamp;
    }

    /**
     * Generated from protobuf field <code>string creation_timestamp = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCreationTimestamp($var)
    {
        GPBUtil::checkString($var, True);
        $this->creation_timestamp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string description = 3;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>string description = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string disk_size_gb = 4;</code>
     * @return string
     */
    public function getDiskSizeGb()
    {
        return $this->disk_size_gb;
    }

    /**
     * Generated from protobuf field <code>string disk_size_gb = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setDiskSizeGb($var)
    {
        GPBUtil::checkString($var, True);
        $this->disk_size_gb = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string download_bytes = 5;</code>
     * @return string
     */
    public function getDownloadBytes()
    {
        return $this->download_bytes;
    }

    /**
     * Generated from protobuf field <code>string download_bytes = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setDownloadBytes($var)
    {
        GPBUtil::checkString($var, True);
        $this->download_bytes = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string id = 6;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string kind = 7;</code>
     * @return string
     */
    public function getKind()
    {
        return $this->kind;
    }

    /**
     * Generated from protobuf field <code>string kind = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setKind($var)
    {
        GPBUtil::checkString($var, True);
        $this->kind = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string label_fingerprint = 8;</code>
     * @return string
     */
    public function getLabelFingerprint()
    {
        return $this->label_fingerprint;
    }

    /**
     * Generated from protobuf field <code>string label_fingerprint = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setLabelFingerprint($var)
    {
        GPBUtil::checkString($var, True);
        $this->label_fingerprint = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, string> labels = 9;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getLabels()
    {
        return $this->labels;
    }

    /**
     * Generated from protobuf field <code>map<string, string> labels = 9;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setLabels($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->labels = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string license_codes = 10;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getLicenseCodes()
    {
        return $this->license_codes;
    }

    /**
     * Generated from protobuf field <code>repeated string license_codes = 10;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setLicenseCodes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->license_codes = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string licenses = 11;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getLicenses()
    {
        return $this->licenses;
    }

    /**
     * Generated from protobuf field <code>repeated string licenses = 11;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setLicenses($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->licenses = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 12;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string self_link = 13;</code>
     * @return string
     */
    public function getSelfLink()
    {
        return $this->self_link;
    }

    /**
     * Generated from protobuf field <code>string self_link = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setSelfLink($var)
    {
        GPBUtil::checkString($var, True);
        $this->self_link = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.CustomerEncryptionKey snapshot_encryption_key = 14;</code>
     * @return \Google\Cloud\Compute\V1\CustomerEncryptionKey
     */
    public function getSnapshotEncryptionKey()
    {
        return $this->snapshot_encryption_key;
    }

    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.CustomerEncryptionKey snapshot_encryption_key = 14;</code>
     * @param \Google\Cloud\Compute\V1\CustomerEncryptionKey $var
     * @return $this
     */
    public function setSnapshotEncryptionKey($var)
    {
        GPBUtil::checkMessage($var, \Google\Cloud\Compute\V1\CustomerEncryptionKey::class);
        $this->snapshot_encryption_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string source_disk = 15;</code>
     * @return string
     */
    public function getSourceDisk()
    {
        return $this->source_disk;
    }

    /**
     * Generated from protobuf field <code>string source_disk = 15;</code>
     * @param string $var
     * @return $this
     */
    public function setSourceDisk($var)
    {
        GPBUtil::checkString($var, True);
        $this->source_disk = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.CustomerEncryptionKey source_disk_encryption_key = 16;</code>
     * @return \Google\Cloud\Compute\V1\CustomerEncryptionKey
     */
    public function getSourceDiskEncryptionKey()
    {
        return $this->source_disk_encryption_key;
    }

    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.CustomerEncryptionKey source_disk_encryption_key = 16;</code>
     * @param \Google\Cloud\Compute\V1\CustomerEncryptionKey $var
     * @return $this
     */
    public function setSourceDiskEncryptionKey($var)
    {
        GPBUtil::checkMessage($var, \Google\Cloud\Compute\V1\CustomerEncryptionKey::class);
        $this->source_disk_encryption_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string source_disk_id = 17;</code>
     * @return string
     */
    public function getSourceDiskId()
    {
        return $this->source_disk_id;
    }

    /**
     * Generated from protobuf field <code>string source_disk_id = 17;</code>
     * @param string $var
     * @return $this
     */
    public function setSourceDiskId($var)
    {
        GPBUtil::checkString($var, True);
        $this->source_disk_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.Snapshot.Status status = 18;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.Snapshot.Status status = 18;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \Google\Cloud\Compute\V1\Snapshot_Status::class);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string storage_bytes = 19;</code>
     * @return string
     */
    public function getStorageBytes()
    {
        return $this->storage_bytes;
    }

    /**
     * Generated from protobuf field <code>string storage_bytes = 19;</code>
     * @param string $var
     * @return $this
     */
    public function setStorageBytes($var)
    {
        GPBUtil::checkString($var, True);
        $this->storage_bytes = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.Snapshot.StorageBytesStatus storage_bytes_status = 20;</code>
     * @return int
     */
    public function getStorageBytesStatus()
    {
        return $this->storage_bytes_status;
    }

    /**
     * Generated from protobuf field <code>.google.cloud.compute.v1.Snapshot.StorageBytesStatus storage_bytes_status = 20;</code>
     * @param int $var
     * @return $this
     */
    public function setStorageBytesStatus($var)
    {
        GPBUtil::checkEnum($var, \Google\Cloud\Compute\V1\Snapshot_StorageBytesStatus::class);
        $this->storage_bytes_status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string storage_locations = 21;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getStorageLocations()
    {
        return $this->storage_locations;
    }

    /**
     * Generated from protobuf field <code>repeated string storage_locations = 21;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setStorageLocations($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->storage_locations = $arr;

        return $this;
    }

}

