<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/compute/v1/compute.proto

namespace Google\Cloud\Compute\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>google.cloud.compute.v1.VpnGatewayStatusTunnel</code>
 */
class VpnGatewayStatusTunnel extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 local_gateway_interface = 1;</code>
     */
    protected $local_gateway_interface = 0;
    /**
     * Generated from protobuf field <code>uint32 peer_gateway_interface = 2;</code>
     */
    protected $peer_gateway_interface = 0;
    /**
     * Generated from protobuf field <code>string tunnel_url = 3;</code>
     */
    protected $tunnel_url = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $local_gateway_interface
     *     @type int $peer_gateway_interface
     *     @type string $tunnel_url
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Cloud\Compute\V1\Compute::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 local_gateway_interface = 1;</code>
     * @return int
     */
    public function getLocalGatewayInterface()
    {
        return $this->local_gateway_interface;
    }

    /**
     * Generated from protobuf field <code>uint32 local_gateway_interface = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setLocalGatewayInterface($var)
    {
        GPBUtil::checkUint32($var);
        $this->local_gateway_interface = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 peer_gateway_interface = 2;</code>
     * @return int
     */
    public function getPeerGatewayInterface()
    {
        return $this->peer_gateway_interface;
    }

    /**
     * Generated from protobuf field <code>uint32 peer_gateway_interface = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setPeerGatewayInterface($var)
    {
        GPBUtil::checkUint32($var);
        $this->peer_gateway_interface = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string tunnel_url = 3;</code>
     * @return string
     */
    public function getTunnelUrl()
    {
        return $this->tunnel_url;
    }

    /**
     * Generated from protobuf field <code>string tunnel_url = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setTunnelUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->tunnel_url = $var;

        return $this;
    }

}

