<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/compute/v1/compute.proto

namespace Google\Cloud\Compute\V1\RouterStatusBgpPeerStatus;

use UnexpectedValueException;

/**
 * Protobuf type <code>google.cloud.compute.v1.RouterStatusBgpPeerStatus.Status</code>
 */
class Status
{
    /**
     * Generated from protobuf enum <code>DOWN = 0;</code>
     */
    const DOWN = 0;
    /**
     * Generated from protobuf enum <code>UNKNOWN = 1;</code>
     */
    const UNKNOWN = 1;
    /**
     * Generated from protobuf enum <code>UP = 2;</code>
     */
    const UP = 2;

    private static $valueToName = [
        self::DOWN => 'DOWN',
        self::UNKNOWN => 'UNKNOWN',
        self::UP => 'UP',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Status::class, \Google\Cloud\Compute\V1\RouterStatusBgpPeerStatus_Status::class);

