<?php
/**
 * Copyright 2016 Google Inc. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

namespace Google\Cloud\Dev\DocGenerator\Parser;

use Google\Cloud\Core\Testing\DocBlockStripSpaces;
use Google\Cloud\Dev\DocGenerator\ReflectorRegister;
use Google\Cloud\Dev\GetComponentsTrait;
use phpDocumentor\Reflection\DocBlock;
use phpDocumentor\Reflection\DocBlock\Description;
use phpDocumentor\Reflection\Element;
use phpDocumentor\Reflection\Fqsen;
use phpDocumentor\Reflection\Type;
use phpDocumentor\Reflection\Types;
use phpDocumentor\Reflection\TypeResolver;
use phpDocumentor\Reflection\Php\Class_;
use phpDocumentor\Reflection\Php\File;
use phpDocumentor\Reflection\Php\Interface_;
use phpDocumentor\Reflection\Php\Method;
use phpDocumentor\Reflection\Php\Project;
use phpDocumentor\Reflection\Php\Trait_;
use phpDocumentor\Reflection\Php\Visibility;
use phpDocumentor\Reflection\DocBlock\Tag;
use Rize\UriTemplate;
use Symfony\Component\Console\Output\OutputInterface;

class CodeParser implements ParserInterface
{
    use GetComponentsTrait;

    const CLASS_TYPE_REGEX = '/[Generator\<]?(Google\\\Cloud\\\[\w\\\]{0,})[\>]?[\[\]]?/';
    const SNIPPET_NAME_REGEX = '/\/\/\s?\[snippet\=(\w{0,})\]/';

    private static $composerFiles = [];
    private static $lockFile;

    private $file;
    private $register;
    private $markdown;
    private $projectRoot;
    private $externalTypes;
    private $componentId;
    private $manifestPath;
    private $release;
    private $isComponent;

    public function __construct(
        File $file,
        ReflectorRegister $register,
        $projectRoot,
        $componentId,
        $manifestPath,
        $release,
        OutputInterface $output,
        $id,
        $isComponent = true
    ) {
        $this->file = $file;
        $this->register = $register;
        $this->markdown = \Parsedown::instance();
        $this->projectRoot = $projectRoot;
        $this->externalTypes = include $this->projectRoot . '/docs/external-classes.php';
        $this->componentId = $componentId;
        $this->manifestPath = $manifestPath;
        $this->release = $release;
        $this->output = $output;
        $this->id = $id;
        $this->isComponent = $isComponent;

        if (!$this->externalTypes) {
            throw new \RuntimeException('Error in external types.');
        }
    }

    public function parse(): ?array
    {
        if (!$element = $this->register->getElementFromFile($this->file)) {
            return null;
        }

        return $this->buildDocument($element);
    }

    private function buildInfo(Element $element): array
    {
        $classInfo = [
            'methods' => [],
            'traits' => [],
            'parents' => [],
            'interfaces' => [],
            'interfaceMethods' => [],
            'isProto' => false
        ];

        $this->buildClassInfoRecursive($element, $classInfo);

        return $classInfo;
    }

    private function buildClassInfoRecursive(
        Element $element,
        array &$classInfo
    ): void {
        $fullName = (string) $element->getFqsen();

        // START proto nested arg missing description workaround
        if (preg_match('/\\V\d{0,}/', $fullName) === 1) {
            $content = $this->file->getSource();
            $lines = explode(PHP_EOL, $content);
            foreach ($lines as $line) {
                if (strpos(trim($line), 'namespace') !== false) {
                    break;
                }

                if (strpos($line, '# Generated by the protocol buffer compiler.  DO NOT EDIT!') !== false) {
                    $classInfo['isProto'] = true;
                    break;
                }
            }
        }
        // END proto nested arg missing description workaround

        $methods = $this->buildMethodInfo($element);

        $isInternal = substr_compare($fullName, '\Google\Cloud', 0, 13) === 0;
        if ($isInternal) {
            $classInfo['methods'] += $methods;
        }

        foreach ($element->getUsedTraits() as $fqsen) {
            if ($trait = $this->register->getElementFromFqsen($fqsen)) {
                $this->buildClassInfoRecursive($trait, $classInfo);
            }
        }

        foreach ($element->getInterfaces() as $fqsen) {
            if ($interface = $this->register->getElementFromFqsen($fqsen)) {
                $this->buildInterfaceInfoRecursive($interface, $classInfo);
            }
        }

        if ($fqsen = $element->getParent()) {
            if ($parent = $this->register->getElementFromFqsen($fqsen)) {
                $this->buildClassInfoRecursive($parent, $classInfo);
                // Add $parent to array after calling getMethodsRecursive so that
                // parents are correctly ordered
                $classInfo['parents'][] = $fqsen;
            }
        }
    }

    private function buildInterfaceInfo(Interface_ $interface): array
    {
        $classInfo = [
            'interfaces' => [],
            'interfaceMethods' => [],
        ];

        $this->buildInterfaceInfoRecursive($interface, $classInfo);

        return $classInfo;
    }

    private function buildInterfaceInfoRecursive(Interface_ $interface, array &$classInfo): void
    {
        $context = $interface->getDocBlock()->getContext();
        $fullName = (string) $interface->getFqsen();
        $isInternal = substr_compare($fullName, '\Google\Cloud', 0, 13) === 0;
        if ($isInternal) {
            $classInfo['interfaceMethods'] += $this->buildMethodInfo($interface);
        }

        // Add parent interfaces to array before calling getMethodsRecursive to use PHP array
        // ordering, so that parent interfaces are before more deeply nested interfaces
        $classInfo['interfaces'] += $interface->getParents();
        foreach ($reflector->getParents() as $parent) {
            if ($interface = $this->register->getElementFromFqsen($parent)) {
                $this->buildInterfaceInfoRecursive($interface, $classInfo);
            }
        }
    }

    private function buildMethodInfo(Element $element): array
    {
        $methods = [];

        $file = $this->register->getFileFromFqsen($element->getFqsen());
        foreach ($element->getMethods() as $name => $method) {
            if ((string) $method->getVisibility() !== Visibility::PUBLIC_) {
                continue;
            }

            $methods[$name] = [
                'method' => $method,
                'source' => $file->getPath(),
                'container' => (string) $element->getFqsen(),
            ];
        }
        return $methods;
    }

    private function buildDocument(Element $element): array
    {
        $docBlock = $element->getDocBlock();

        if (is_null($docBlock)) {
            throw new \LogicException(sprintf('No description (%s)', $this->file->getPath()));
        }

        $context = $docBlock->getContext();
        $fullName = (string) $element->getFqsen();
        $type = strtolower($element->getName()); // I have no clue what this is

        $magic = [];
        if ($docBlock && $docBlock->getTags()) {
            $magicMethods = array_filter($docBlock->getTags(), function ($tag) {
                return ($tag->getName() === 'method');
            });

            $magic = $this->buildMagicMethods($magicMethods, $fullName);
        }

        $description = $docBlock->getDescription();
        $split = $this->splitDescription($description);

        if ($element instanceof Interface_) {
            $classInfo = $this->buildInterfaceInfo($reflector);
            $description = $this->buildInterfaceDescription($classInfo, $description, $split['description'], $element);
            $methods = $this->buildMethods($classInfo['interfaceMethods'], $fullName);
        } else {
            $classInfo = $this->buildInfo($element);
            $description = $this->buildClassDescription($classInfo, $description, $split['description'], $element);
            $methods = $this->buildMethods($classInfo['methods'], $fullName, $classInfo['isProto']);
        }

        $examples = $split['examples'] ? $this->buildExamples($split['examples']) : null;

        return [
            'id' => $this->id,
            'type' => $type,
            'title' => $fullName,
            'name' => $name,
            'description' => $description,
            'examples' => $examples,
            'resources' => $this->buildResources($docBlock->getTagsByName('see')),
            'methods' => array_merge($methods, $magic)
        ];
    }

    private function buildDescription(
        Description $description,
        $content = null,
        Element $element = null
    ): string {
        return $this->markdown->parse(
            $this->buildDescriptionContent(
                $description,
                $content,
                $element
            )
        );
    }

    private function buildClassDescription(
        array $classInfo,
        Description $description,
        $content = null,
        Element $element = null
    ): string {
        $content = $this->buildDescriptionContent($description, $content, $element);
        $content .= $this->buildInheritDoc($classInfo);
        return $this->markdown->parse($content);
    }

    private function buildInterfaceDescription(
        $classInfo,
        Description $description,
        string $content = null,
        Element $element = null
    ): string {
        $content = $this->buildDescriptionContent($description, $content, $element);
        $content .= $this->buildInterfaceInheritDoc($classInfo);
        return $this->markdown->parse($content);
    }

    private function buildDescriptionContent(
        Description $description,
        string $content = null,
        Element $element = null
    ): string {
        if ($content === null) {
            $content = $description->getBodyTemplate();
        }

        $tags = $description->getTags();

        if (count($tags) > 1) {
            // convert inline {@see} tag to custom type link
            foreach ($tags as $tag) {
                if ($tag instanceof Tag\See) {
                    $tag = $this->buildReference((string) $tag->getReference());
                } elseif (strtolower($tag->getName()) === 'inheritdoc') {
                    if ($element === null) {
                        throw new \Exception(sprintf(
                            "Inherit Doc tag ({@inheritdoc}) is only supported when \$element is not null.\nContext:\n%s",
                            $content));
                    }

                    if (!($element instanceof Class_)) {
                        throw new \Exception(sprintf(
                            "Inherit Doc tag ({@inheritdoc}) is not supported for reflector type %s (found in: %s)."
                            . "\nContext:\n%s", get_class($element), $element->getName(), $content));
                    }

                    if (!$parent = $element->getParent()) {
                        throw new \Exception(sprintf('%s has {@inheritdoc} tag but no parent class', $element->getName()));
                    }
                    $parentElement = $this->register->getElementFromFqsen($parent);

                    $parentDesc = $parentElement->getDocBlock()->getDescription();
                    $parentDocSplit = $this->splitDescription($parentDesc);
                    $part = $this->buildDescriptionContent(
                        $parentDesc,
                        $parentDocSplit['description'],
                        $parentElement
                    );
                }
            }

            $content = implode('', $parsedContents);
        }

        $content = str_ireplace('[optional]', '', $content);
        return $content;
    }

    private function buildReference(string $type): string
    {
        if ($this->hasInternalType($type)) {
            return $this->buildInternalLink($type);
        }

        if ($this->hasExternalType($type)) {
            return $this->buildExternalLink($type);
        }

        return $type;
    }

    private function buildInheritDoc($classInfo): string
    {
        $content = '';
        if (count($classInfo['parents']) > 0) {
            $content .= $this->implodeInheritDocLinks(" &raquo; ", $classInfo['parents'], "Extends");
        }
        if (count($classInfo['interfaces']) > 0) {
            $content .= $this->implodeInheritDocLinks(", ", $classInfo['interfaces'], "Implements");
        }

        return $content;
    }

    private function buildInterfaceInheritDoc(array $classInfo): string
    {
        $content = '';
        if (count($classInfo['interfaces']) > 0) {
            $content .= $this->implodeInheritDocLinks(", ", $classInfo['interfaces'], "Extends");
        }

        return $content;
    }

    private function implodeInheritDocLinks(
        string $glue,
        array $pieces,
        string $prefix
    ): string {
        return "\n\n$prefix " . implode($glue, array_map([$this, 'buildReference'], $pieces));
    }

    private function buildMethods(
        array $methods,
        string $className,
        bool $isProto = false
    ): array {
        $methodArray = [];
        foreach ($methods as $name => $methodInfo) {
            $method = $methodInfo['method'];

            if ((string) $method->getVisibility() !== Visibility::PUBLIC_) {
                continue;
            }

            $docBlock = $method->getDocBlock();
            if (is_null($docBlock)) {
                if (!$isProto && $name === '__construct') {
                    $this->output->writeln(sprintf('%s::%s has no description', $className, $name));
                }
                continue;
            }

            $access = $docBlock->getTagsByName('access');

            if (!empty($access)) {
                if ($access[0]->getContent() === 'private') {
                    continue;
                }
            }

            $methodArray[] = $this->buildMethod($method, $methodInfo, $className, $isProto);
        }

        return $methodArray;
    }

    private function buildMagicMethods(
        array $magicMethods,
        string $className
    ): array {
        $methodArray = [];
        foreach ($magicMethods as $method) {
            if (!$description = $method->getDescription()) {
                throw new \Exception(sprintf(
                    '%s::%s (magic method) has no description',
                    $className,
                    $method->getMethodName()
                ));
            }

            $methodArray[] = $this->buildMagicMethod($method, $className);
        }

        return $methodArray;
    }

    private function buildMethod(
        Method $method,
        array $methodInfo,
        string $className,
        bool $isProto = false
    ): array {
        $docBlock = $method->getDocBlock();
        $dscription = $docBlock->getDescription();
        $resources = $docBlock->getTagsByName('see');
        $params = $docBlock->getTagsByName('param');
        $exceptions = $docBlock->getTagsByName('throws');
        $returns = $docBlock->getTagsByName('return');
        $examples = null;

        $split = $this->splitDescription($dscription);
        $examples = $split['examples'] ? $this->buildExamples($split['examples']) : [];

        $description = $this->buildDescription($dscription, $split['description'], $method);
        if ($methodInfo['container'] !== $className) {
            $description .= "\n\nImplemented in " . $this->buildReference($methodInfo['container']);
        }

        return [
            'id' => $method->getName(),
            'type' => $method->getName() === '__construct' ? 'constructor' : 'instance',
            'name' => $method->getName(),
            'source' => $this->getSource($methodInfo['source']) . '#L' . $method->getLocation()->getLineNumber(),
            'description' => $description,
            'examples' => $examples,
            'resources' => $this->buildResources($resources),
            'params' => $this->buildParams($params, $description, $isProto),
            'exceptions' => $this->buildExceptions($exceptions),
            'returns' => $this->buildReturns($returns, $className)
        ];
    }

    private function buildMagicMethod(Method $magicMethod): array
    {
        $docBlock = new DocBlockStripSpaces(substr($magicMethod->getDescription(), 1, -1));
        $fullDescription = $docBlock->getDescription();
        $resources = $docBlock->getTagsByName('see');
        $params = $docBlock->getTagsByName('param');
        $exceptions = $docBlock->getTagsByName('throws');
        $returns = $docBlock->getTagsByName('return');
        $examples = null;

        $parts = explode('Example:', $fullDescription);

        $docText = $parts[0];

        if (strpos($fullDescription, 'Example:') !== false) {
            $examples = $parts[1];
        }

        return [
            'id' => $magicMethod->getMethodName(),
            'type' => $magicMethod->getMethodName() === '__construct' ? 'constructor' : 'instance',
            'name' => $magicMethod->getMethodName(),
            'source' => $this->getSource($this->path),
            'description' => $this->buildDescription($docBlock, $docText, $magicMethod),
            'examples' => $this->buildExamples($examples),
            'resources' => $this->buildResources($resources),
            'params' => $this->buildParams($params),
            'exceptions' => $this->buildExceptions($exceptions),
            'returns' => $this->buildReturns($returns)
        ];
    }

    private function buildExamples(array $examples): array
    {
        $examplesArray = [];

        if (!$examples) {
            return $examplesArray;
        }

        $exampleParts = explode('```', $examples);

        foreach ($exampleParts as $example) {
            $example = trim($example);
            $caption = '';

            if (strlen($example) === 0) {
                continue;
            }

            $example = preg_replace(self::SNIPPET_NAME_REGEX, '', $example);
            $lines = explode(PHP_EOL, trim($example));

            // strip the syntax highlighting, it won't be used in the doc site
            if (substr($lines[0], 0, 3) === 'php') {
                unset($lines[0]);
            }

            $captionLines = [];
            foreach ($lines as $key => $line) {
                if (substr($line, 0, 2) === '//') {
                    $captionLines[] = substr($line, 3);
                    unset($lines[$key]);
                } else {
                    break;
                }
            }

            $caption = $this->markdown->parse(implode(' ', $captionLines));

            $examplesArray[] = [
                'caption' => $caption,
                'code' => trim(implode(PHP_EOL, $lines))
            ];
        }

        return $examplesArray;
    }

    private function buildResources(array $resources): array
    {
        if (count($resources) === 0) {
            return $resources;
        }

        $resourcesArray = [];

        foreach ($resources as $resource) {
            $resourcesArray[] = [
                'title' => $resource->getDescription(),
                'link' => $resource->getReference()
            ];
        }

        return $resourcesArray;
    }

    private function buildParams(
        array $params,
        string $methodDescription = null,
        bool $isProto = false
    ): array {
        if (count($params) === 0) {
            return $params;
        }

        $paramsArray = [];

        foreach ($params as $param) {
            $description = $param->getDescription();
            $descriptionString = $this->buildDescription($description);

            $nestedParamsArray = [];

            // To handle generated protobuf files
            if ($descriptionString === '' && $methodDescription) {
                $pos = strpos($methodDescription, '<p>Generated from protobuf field');
                if ($pos) {
                    $descriptionString = substr($methodDescription, 0, $pos);
                }
            }

            if (strpos($param->getType(), 'array') === 0 && $this->hasNestedParams($description)) {
                $nestedParamString = trim(str_replace('[optional]', '', $description));
                $nestedParamString = substr($nestedParamString, 1, -1);
                $nestedParams = explode('@type', $nestedParamString);
                $nestedParamString = trim(array_shift($nestedParams));
                $nestedParamsArray = $this->buildNestedParams($nestedParams, $param, $isProto);
                $description = $param->getDescription();

                $descriptionString = $this->buildDescription($description);
            }

            if (!$varName = $param->getVariableName()) {
                throw new \Exception(sprintf(
                    'invalid or missing parameter name in "%s"',
                    $param->getDocBlock()->getShortDescription()
                ));
            }
            $paramsArray[] = [
                'name' => $varName,
                'description' => $descriptionString,
                'types' => $this->handleTypes([$param->getType()]),
                'optional' => (strpos(trim(strtolower($description)), '[optional]') === 0),
                'nullable' => null // @todo
            ];

            $paramsArray = array_merge($paramsArray, $nestedParamsArray);
        }

        return $paramsArray;
    }

    /**
     * PHPDoc has no support for nested params currently. this is a workaround
     * until it is implemented.
     */
    private function buildNestedParams(
        array $nestedParams,
        Tag $origParam,
        bool $isProto = false
    ): array {
        $paramsArray = [];
        $typeResolver = new TypeResolver();

        foreach ($nestedParams as $param) {
            $nestedParam = explode(' ', trim($param), 3);

            // START proto nested arg missing description workaround
            if (count($nestedParam) < 3 && !$isProto) {
                $this->output->writeln('nested param is in an invalid format: '. $param);
            }
            // END proto nested arg missing description workaround

            list($type, $name, $content) = $nestedParam;
            $name = substr($name, 1);
            $content = preg_replace('/\s+/', ' ', $content);
            $description = $origParam->getDescription();

            $paramsArray[] = [
                'name' => substr($origParam->getVariableName(), 1) . '.' . $name,
                'description' => $this->buildDescription($description, $content),
                'types' => $this->handleTypes([$typeResolver->resolve($type)]),
                'optional' => null, // @todo
                'nullable' => null //@todo
            ];
        }

        return $paramsArray;
    }

    private function hasNestedParams(string $description): bool
    {
        $description = trim(str_replace('[optional]', '', $description));

        if (strlen($description) === 0) {
            return false;
        }

        return $description[0] === '{';
    }

    private function buildExceptions(array $exceptions): array
    {
        if (count($exceptions) === 0) {
            return $exceptions;
        }

        $exceptionsArray = [];

        foreach ($exceptions as $exception) {
            $exceptionsArray[] = [
                'type' => $exception->getType(),
                'description' => $exception->getDescription()
            ];
        }

        return $exceptionsArray;
    }

    private function buildReturns(array $returns, string $className = null): array
    {
        if (count($returns) === 0) {
            return $returns;
        }

        $returnsArray = [];

        foreach ($returns as $return) {
            $returnsArray[] = [
                'types' => $this->handleTypes(
                    [$return->getType()],
                    null,
                    $className
                ),
                'description' => $this->buildDescription($return->getDescription(), null)
            ];
        }

        return $returnsArray;
    }

    private function handleTypes(
        array $types,
        string $context = null,
        string $className = null
    ): array {
        $res = [];

        foreach ($types as $type) {
            $res[] = $this->handleType($type, $context, $className);
        }

        return $res;
    }

    private function handleType(Type $type, ?string $context, ?string $className): string
    {
        $matches = [];
        if (preg_match('/\\\\?(.*?)\<(.*?)\>/', (string) $type, $matches)) {
            $aliases = $context
                ? $context->getNamespaceAliases()
                : [];
            $namespace = $context
                ? $context->getNamespace()
                : null;
            $matches[1] = $this->buildReference(
                $this->resolveTypeAlias($matches[1], $aliases, $namespace)
            );
            $matches[2] = $this->buildReference(
                $this->resolveTypeAlias($matches[2], $aliases, $namespace)
            );

            return sprintf(htmlentities('%s<%s>'), $matches[1], $matches[2]);
        }

        if ($type instanceof Types\This) {
            return $this->buildReference($className);
        }

        if ($type instanceof Types\AggregatedType) {
            $typeRefs = [];
            foreach ($type as $aggregatedType) {
                $typeRefs[] = $this->buildReference((string) $aggregateType);
            }
            return implode('|', $typeRefs);
        }

        return $this->buildReference((string) $type);
    }

    private function resolveTypeAlias(
        string $type,
        array $aliases,
        string $namespace = null
    ) {
        $pieces = explode('\\', $type);
        $basename = array_pop($pieces);
        if (array_key_exists($basename, $aliases)) {
            $type = $aliases[$basename];
        } elseif (count(explode('\\', $type)) === 1) {
            if (class_exists($namespace .'\\'. $type)) {
                $type = $namespace .'\\'. $type;
            }
        }

        return $type;
    }

    private function hasInternalType(string $fqsen): bool
    {
        if (substr_compare($fqsen, '\\Google\\Cloud', 0, 12) === 0) {
            $file = $this->register->getFileFromFqsen(new Fqsen($fqsen));

            $vendorPath = $this->projectRoot . 'vendor';
            if (substr($file->getPath(), 0, strlen($vendorPath)) === $vendorPath) {
                return false;
            }

            return true;
        }

        return false;
    }

    private function hasExternalType(string $fqsen): bool
    {
        $type = trim($fqsen, '\\');
        $types = array_filter($this->externalTypes, function ($external) use ($type) {
            return (strpos($type, $external['name']) !== false);
        });

        return count($types) !== 0;
    }

    private function buildExternalLink(string $type): string
    {
        $type = trim($type, '\\');
        $types = array_values(array_filter($this->externalTypes, function ($external) use ($type) {
            return (strpos($type, $external['name']) !== false);
        }));

        $external = $types[0];

        $name = $type;
        if (strpos('\\', $type) !== false) {
            $type = str_replace(
                $external['name'],
                '',
                str_replace('[]', '', $type)
            );
        }

        $type = str_replace('\\', '/', $type);

        $placeholders = [];

        if (isset($external['depName'])) {
            list (
                $type,
                $placeholders['depVersion']
             ) = $this->getExternalDepVersion($type, $external);
        }

        // strip method reference from external type, since we can't predict
        // with certainty how method anchors work.
        $type = explode('::', $type)[0];

        $placeholders['type'] = explode('/', $type);

        $uri = new UriTemplate;
        $href = $uri->expand($external['uri'], $placeholders);

        return sprintf(
            '<a href="%s" target="_blank">%s</a>',
            $href,
            $name
        );
    }

    private function getExternalDepVersion(string $type, array $external): array
    {
        $depName = $external['depName'];

        $lockFilePath = $this->projectRoot . '/composer.lock';
        if (!self::$lockFile && file_exists($lockFilePath)) {
            self::$lockFile = json_decode(file_get_contents($lockFilePath), true)['packages'];
        } elseif (!file_exists($lockFilePath)) {
            throw new \RuntimeException('composer.lock file does not exist. Run `composer install` first.');
        }

        $dep = array_values(array_filter(self::$lockFile, function ($package) use ($depName) {
            return $package['name'] === $depName;
        }));

        if (!$dep) {
            throw new \RuntimeException(sprintf(
                'Could not find installed package %s. Check `docs/external-classes.json` to verify.',
                $depName
            ));
        }

        if (isset($external['strip']) && $external['strip']) {
            $type = str_replace(
                str_replace('\\', '/', $external['name']),
                '',
                $type
            );
        }

        return [
            $type,
            $dep[0]['version']
        ];
    }

    private function buildInternalLink(string $type): string
    {
        $fqsen = rtrim($type, '[]');
        $componentId = null;
        $file = $this->register->getFileFromFqsen(new Fqsen($fqsen));
        $fileName = $file->getPath();

        if ($this->isComponent) {
            $composer = $this->getComponentComposerFile($fileName);
            $componentId = $composer['extra']['component']['id'];
        }

        $parts = explode('::', $fqsen);
        $type = $this->fileNameToType($fileName);

        if ($componentId) {
            $version = ($this->release)
                ? $this->getComponentVersion($this->manifestPath, $componentId)
                : 'master';

            $type = $componentId .'/'. $version .'/'. $type;
        }

        $openTag = "<a data-custom-type=\"$type\"";

        if (isset($parts[1])) {
            $method = str_replace('()', '', $parts[1]);
            $openTag .= " data-method=\"$method\">";
        } else {
            $openTag .= '>';
        }

        return sprintf('%s%s</a>', $openTag, trim($type, '\\'));
    }

    private function getComponentComposerFile(string $fileName): array
    {
        $originalFileName = $fileName;
        $recurse = true;

        do {
            $composer = dirname($fileName) .'/composer.json';
            if (file_exists($composer)) {
                if (isset(self::$composerFiles[$composer])) {
                    return self::$composerFiles[$composer];
                }

                $contents = json_decode(file_get_contents($composer), true);

                if (isset($contents['extra']['component'])) {
                    self::$composerFiles[$composer] = $contents;
                    return $contents;
                }

                $recurse = false;
            } elseif (trim($fileName, '/') === trim($this->projectRoot, '/')) {
                $recurse = false;
            } else {
                $fileName = dirname($fileName);
            }
        } while($recurse);

        throw new \Exception(sprintf(
            'Unable to find composer file for %s',
            $originalFileName
        ));
    }

    private function fileNameToType(string $fileName): string
    {
        return str_replace('src/', '', substr(
            strtolower($fileName),
            strlen($this->projectRoot),
            -4
        ));
    }

    private function splitDescription(Description $description): array
    {
        $examples = null;
        $parts = [];
        $body = $description->getBodyTemplate();

        if (strpos($body, 'Example:' . PHP_EOL . '```') !== false) {
            $parts = explode('Example:' . PHP_EOL, $body);
            $examples = $parts[1];
        }

        return [
            'description' => $parts[0],
            'examples' => $examples
        ];
    }

    private function getSource(string $path): string
    {
        $filePieces = explode('/', $path);

        $srcIdx = [];
        array_walk($filePieces, function ($piece, $i) use (&$srcIdx) {
            if ($piece === 'src') {
                $srcIdx[] = $i;
            }
        });

        // Just in case you're running inside a different src directory...
        $realSrcIndex = end($srcIdx);

        $base = $realSrcIndex - 1;

        return implode('/', array_slice($filePieces, $base));
    }
}
