<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/compute/v1/compute.proto

namespace Google\Cloud\Compute\V1\RawDisk;

use UnexpectedValueException;

/**
 * Protobuf type <code>google.cloud.compute.v1.RawDisk.ContainerType</code>
 */
class ContainerType
{
    /**
     * Generated from protobuf enum <code>TAR = 0;</code>
     */
    const TAR = 0;

    private static $valueToName = [
        self::TAR => 'TAR',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(ContainerType::class, \Google\Cloud\Compute\V1\RawDisk_ContainerType::class);

