<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/compute/v1/compute.proto

namespace Google\Cloud\Compute\V1\TargetInstance;

use UnexpectedValueException;

/**
 * Protobuf type <code>google.cloud.compute.v1.TargetInstance.NatPolicy</code>
 */
class NatPolicy
{
    /**
     * Generated from protobuf enum <code>NO_NAT = 0;</code>
     */
    const NO_NAT = 0;

    private static $valueToName = [
        self::NO_NAT => 'NO_NAT',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(NatPolicy::class, \Google\Cloud\Compute\V1\TargetInstance_NatPolicy::class);

