<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/compute/v1/compute.proto

namespace Google\Cloud\Compute\V1\TargetHttpsProxy;

use UnexpectedValueException;

/**
 * Protobuf type <code>google.cloud.compute.v1.TargetHttpsProxy.QuicOverride</code>
 */
class QuicOverride
{
    /**
     * Generated from protobuf enum <code>DISABLE = 0;</code>
     */
    const DISABLE = 0;
    /**
     * Generated from protobuf enum <code>ENABLE = 1;</code>
     */
    const ENABLE = 1;
    /**
     * Generated from protobuf enum <code>NONE = 2;</code>
     */
    const NONE = 2;

    private static $valueToName = [
        self::DISABLE => 'DISABLE',
        self::ENABLE => 'ENABLE',
        self::NONE => 'NONE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(QuicOverride::class, \Google\Cloud\Compute\V1\TargetHttpsProxy_QuicOverride::class);

