<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/compute/v1/compute.proto

namespace Google\Cloud\Compute\V1\AuditLogConfig;

use UnexpectedValueException;

/**
 * Protobuf type <code>google.cloud.compute.v1.AuditLogConfig.LogType</code>
 */
class LogType
{
    /**
     * Generated from protobuf enum <code>ADMIN_READ = 0;</code>
     */
    const ADMIN_READ = 0;
    /**
     * Generated from protobuf enum <code>DATA_READ = 1;</code>
     */
    const DATA_READ = 1;
    /**
     * Generated from protobuf enum <code>DATA_WRITE = 2;</code>
     */
    const DATA_WRITE = 2;
    /**
     * Generated from protobuf enum <code>LOG_TYPE_UNSPECIFIED = 3;</code>
     */
    const LOG_TYPE_UNSPECIFIED = 3;

    private static $valueToName = [
        self::ADMIN_READ => 'ADMIN_READ',
        self::DATA_READ => 'DATA_READ',
        self::DATA_WRITE => 'DATA_WRITE',
        self::LOG_TYPE_UNSPECIFIED => 'LOG_TYPE_UNSPECIFIED',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(LogType::class, \Google\Cloud\Compute\V1\AuditLogConfig_LogType::class);

