<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/compute/v1/compute.proto

namespace Google\Cloud\Compute\V1\Address;

use UnexpectedValueException;

/**
 * Protobuf type <code>google.cloud.compute.v1.Address.AddressType</code>
 */
class AddressType
{
    /**
     * Generated from protobuf enum <code>EXTERNAL = 0;</code>
     */
    const EXTERNAL = 0;
    /**
     * Generated from protobuf enum <code>INTERNAL = 1;</code>
     */
    const INTERNAL = 1;
    /**
     * Generated from protobuf enum <code>UNSPECIFIED_TYPE = 2;</code>
     */
    const UNSPECIFIED_TYPE = 2;

    private static $valueToName = [
        self::EXTERNAL => 'EXTERNAL',
        self::INTERNAL => 'INTERNAL',
        self::UNSPECIFIED_TYPE => 'UNSPECIFIED_TYPE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(AddressType::class, \Google\Cloud\Compute\V1\Address_AddressType::class);

