<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/compute/v1/compute.proto

namespace Google\Cloud\Compute\V1\Address;

use UnexpectedValueException;

/**
 * Protobuf type <code>google.cloud.compute.v1.Address.IpVersion</code>
 */
class IpVersion
{
    /**
     * Generated from protobuf enum <code>IPV4 = 0;</code>
     */
    const IPV4 = 0;
    /**
     * Generated from protobuf enum <code>IPV6 = 1;</code>
     */
    const IPV6 = 1;
    /**
     * Generated from protobuf enum <code>UNSPECIFIED_VERSION = 2;</code>
     */
    const UNSPECIFIED_VERSION = 2;

    private static $valueToName = [
        self::IPV4 => 'IPV4',
        self::IPV6 => 'IPV6',
        self::UNSPECIFIED_VERSION => 'UNSPECIFIED_VERSION',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(IpVersion::class, \Google\Cloud\Compute\V1\Address_IpVersion::class);

