<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/compute/v1/compute.proto

namespace Google\Cloud\Compute\V1\InterconnectLocation;

use UnexpectedValueException;

/**
 * Protobuf type <code>google.cloud.compute.v1.InterconnectLocation.Status</code>
 */
class Status
{
    /**
     * Generated from protobuf enum <code>AVAILABLE = 0;</code>
     */
    const AVAILABLE = 0;
    /**
     * Generated from protobuf enum <code>CLOSED = 1;</code>
     */
    const CLOSED = 1;

    private static $valueToName = [
        self::AVAILABLE => 'AVAILABLE',
        self::CLOSED => 'CLOSED',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Status::class, \Google\Cloud\Compute\V1\InterconnectLocation_Status::class);

