<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/compute/v1/compute.proto

namespace Google\Cloud\Compute\V1\ResourceCommitment;

use UnexpectedValueException;

/**
 * Protobuf type <code>google.cloud.compute.v1.ResourceCommitment.Type</code>
 */
class Type
{
    /**
     * Generated from protobuf enum <code>ACCELERATOR = 0;</code>
     */
    const ACCELERATOR = 0;
    /**
     * Generated from protobuf enum <code>LOCAL_SSD = 1;</code>
     */
    const LOCAL_SSD = 1;
    /**
     * Generated from protobuf enum <code>MEMORY = 2;</code>
     */
    const MEMORY = 2;
    /**
     * Generated from protobuf enum <code>UNSPECIFIED = 3;</code>
     */
    const UNSPECIFIED = 3;
    /**
     * Generated from protobuf enum <code>VCPU = 4;</code>
     */
    const VCPU = 4;

    private static $valueToName = [
        self::ACCELERATOR => 'ACCELERATOR',
        self::LOCAL_SSD => 'LOCAL_SSD',
        self::MEMORY => 'MEMORY',
        self::UNSPECIFIED => 'UNSPECIFIED',
        self::VCPU => 'VCPU',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Type::class, \Google\Cloud\Compute\V1\ResourceCommitment_Type::class);

