<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/compute/v1/compute.proto

namespace Google\Cloud\Compute\V1\AutoscalerStatusDetails;

use UnexpectedValueException;

/**
 * Protobuf type <code>google.cloud.compute.v1.AutoscalerStatusDetails.Type</code>
 */
class Type
{
    /**
     * Generated from protobuf enum <code>ALL_INSTANCES_UNHEALTHY = 0;</code>
     */
    const ALL_INSTANCES_UNHEALTHY = 0;
    /**
     * Generated from protobuf enum <code>BACKEND_SERVICE_DOES_NOT_EXIST = 1;</code>
     */
    const BACKEND_SERVICE_DOES_NOT_EXIST = 1;
    /**
     * Generated from protobuf enum <code>CAPPED_AT_MAX_NUM_REPLICAS = 2;</code>
     */
    const CAPPED_AT_MAX_NUM_REPLICAS = 2;
    /**
     * Generated from protobuf enum <code>CUSTOM_METRIC_DATA_POINTS_TOO_SPARSE = 3;</code>
     */
    const CUSTOM_METRIC_DATA_POINTS_TOO_SPARSE = 3;
    /**
     * Generated from protobuf enum <code>CUSTOM_METRIC_INVALID = 4;</code>
     */
    const CUSTOM_METRIC_INVALID = 4;
    /**
     * Generated from protobuf enum <code>MIN_EQUALS_MAX = 5;</code>
     */
    const MIN_EQUALS_MAX = 5;
    /**
     * Generated from protobuf enum <code>MISSING_CUSTOM_METRIC_DATA_POINTS = 6;</code>
     */
    const MISSING_CUSTOM_METRIC_DATA_POINTS = 6;
    /**
     * Generated from protobuf enum <code>MISSING_LOAD_BALANCING_DATA_POINTS = 7;</code>
     */
    const MISSING_LOAD_BALANCING_DATA_POINTS = 7;
    /**
     * Generated from protobuf enum <code>MODE_OFF = 8;</code>
     */
    const MODE_OFF = 8;
    /**
     * Generated from protobuf enum <code>MODE_ONLY_UP = 9;</code>
     */
    const MODE_ONLY_UP = 9;
    /**
     * Generated from protobuf enum <code>MORE_THAN_ONE_BACKEND_SERVICE = 10;</code>
     */
    const MORE_THAN_ONE_BACKEND_SERVICE = 10;
    /**
     * Generated from protobuf enum <code>NOT_ENOUGH_QUOTA_AVAILABLE = 11;</code>
     */
    const NOT_ENOUGH_QUOTA_AVAILABLE = 11;
    /**
     * Generated from protobuf enum <code>REGION_RESOURCE_STOCKOUT = 12;</code>
     */
    const REGION_RESOURCE_STOCKOUT = 12;
    /**
     * Generated from protobuf enum <code>SCALING_TARGET_DOES_NOT_EXIST = 13;</code>
     */
    const SCALING_TARGET_DOES_NOT_EXIST = 13;
    /**
     * Generated from protobuf enum <code>UNKNOWN = 14;</code>
     */
    const UNKNOWN = 14;
    /**
     * Generated from protobuf enum <code>UNSUPPORTED_MAX_RATE_LOAD_BALANCING_CONFIGURATION = 15;</code>
     */
    const UNSUPPORTED_MAX_RATE_LOAD_BALANCING_CONFIGURATION = 15;
    /**
     * Generated from protobuf enum <code>ZONE_RESOURCE_STOCKOUT = 16;</code>
     */
    const ZONE_RESOURCE_STOCKOUT = 16;

    private static $valueToName = [
        self::ALL_INSTANCES_UNHEALTHY => 'ALL_INSTANCES_UNHEALTHY',
        self::BACKEND_SERVICE_DOES_NOT_EXIST => 'BACKEND_SERVICE_DOES_NOT_EXIST',
        self::CAPPED_AT_MAX_NUM_REPLICAS => 'CAPPED_AT_MAX_NUM_REPLICAS',
        self::CUSTOM_METRIC_DATA_POINTS_TOO_SPARSE => 'CUSTOM_METRIC_DATA_POINTS_TOO_SPARSE',
        self::CUSTOM_METRIC_INVALID => 'CUSTOM_METRIC_INVALID',
        self::MIN_EQUALS_MAX => 'MIN_EQUALS_MAX',
        self::MISSING_CUSTOM_METRIC_DATA_POINTS => 'MISSING_CUSTOM_METRIC_DATA_POINTS',
        self::MISSING_LOAD_BALANCING_DATA_POINTS => 'MISSING_LOAD_BALANCING_DATA_POINTS',
        self::MODE_OFF => 'MODE_OFF',
        self::MODE_ONLY_UP => 'MODE_ONLY_UP',
        self::MORE_THAN_ONE_BACKEND_SERVICE => 'MORE_THAN_ONE_BACKEND_SERVICE',
        self::NOT_ENOUGH_QUOTA_AVAILABLE => 'NOT_ENOUGH_QUOTA_AVAILABLE',
        self::REGION_RESOURCE_STOCKOUT => 'REGION_RESOURCE_STOCKOUT',
        self::SCALING_TARGET_DOES_NOT_EXIST => 'SCALING_TARGET_DOES_NOT_EXIST',
        self::UNKNOWN => 'UNKNOWN',
        self::UNSUPPORTED_MAX_RATE_LOAD_BALANCING_CONFIGURATION => 'UNSUPPORTED_MAX_RATE_LOAD_BALANCING_CONFIGURATION',
        self::ZONE_RESOURCE_STOCKOUT => 'ZONE_RESOURCE_STOCKOUT',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Type::class, \Google\Cloud\Compute\V1\AutoscalerStatusDetails_Type::class);

