<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/compute/v1/compute.proto

namespace Google\Cloud\Compute\V1\Warning;

use UnexpectedValueException;

/**
 * Protobuf type <code>google.cloud.compute.v1.Warning.Code</code>
 */
class Code
{
    /**
     * Generated from protobuf enum <code>CLEANUP_FAILED = 0;</code>
     */
    const CLEANUP_FAILED = 0;
    /**
     * Generated from protobuf enum <code>DEPRECATED_RESOURCE_USED = 1;</code>
     */
    const DEPRECATED_RESOURCE_USED = 1;
    /**
     * Generated from protobuf enum <code>DEPRECATED_TYPE_USED = 2;</code>
     */
    const DEPRECATED_TYPE_USED = 2;
    /**
     * Generated from protobuf enum <code>DISK_SIZE_LARGER_THAN_IMAGE_SIZE = 3;</code>
     */
    const DISK_SIZE_LARGER_THAN_IMAGE_SIZE = 3;
    /**
     * Generated from protobuf enum <code>EXPERIMENTAL_TYPE_USED = 4;</code>
     */
    const EXPERIMENTAL_TYPE_USED = 4;
    /**
     * Generated from protobuf enum <code>EXTERNAL_API_WARNING = 5;</code>
     */
    const EXTERNAL_API_WARNING = 5;
    /**
     * Generated from protobuf enum <code>FIELD_VALUE_OVERRIDEN = 6;</code>
     */
    const FIELD_VALUE_OVERRIDEN = 6;
    /**
     * Generated from protobuf enum <code>INJECTED_KERNELS_DEPRECATED = 7;</code>
     */
    const INJECTED_KERNELS_DEPRECATED = 7;
    /**
     * Generated from protobuf enum <code>MISSING_TYPE_DEPENDENCY = 8;</code>
     */
    const MISSING_TYPE_DEPENDENCY = 8;
    /**
     * Generated from protobuf enum <code>NEXT_HOP_ADDRESS_NOT_ASSIGNED = 9;</code>
     */
    const NEXT_HOP_ADDRESS_NOT_ASSIGNED = 9;
    /**
     * Generated from protobuf enum <code>NEXT_HOP_CANNOT_IP_FORWARD = 10;</code>
     */
    const NEXT_HOP_CANNOT_IP_FORWARD = 10;
    /**
     * Generated from protobuf enum <code>NEXT_HOP_INSTANCE_NOT_FOUND = 11;</code>
     */
    const NEXT_HOP_INSTANCE_NOT_FOUND = 11;
    /**
     * Generated from protobuf enum <code>NEXT_HOP_INSTANCE_NOT_ON_NETWORK = 12;</code>
     */
    const NEXT_HOP_INSTANCE_NOT_ON_NETWORK = 12;
    /**
     * Generated from protobuf enum <code>NEXT_HOP_NOT_RUNNING = 13;</code>
     */
    const NEXT_HOP_NOT_RUNNING = 13;
    /**
     * Generated from protobuf enum <code>NOT_CRITICAL_ERROR = 14;</code>
     */
    const NOT_CRITICAL_ERROR = 14;
    /**
     * Generated from protobuf enum <code>NO_RESULTS_ON_PAGE = 15;</code>
     */
    const NO_RESULTS_ON_PAGE = 15;
    /**
     * Generated from protobuf enum <code>REQUIRED_TOS_AGREEMENT = 16;</code>
     */
    const REQUIRED_TOS_AGREEMENT = 16;
    /**
     * Generated from protobuf enum <code>RESOURCE_IN_USE_BY_OTHER_RESOURCE_WARNING = 17;</code>
     */
    const RESOURCE_IN_USE_BY_OTHER_RESOURCE_WARNING = 17;
    /**
     * Generated from protobuf enum <code>RESOURCE_NOT_DELETED = 18;</code>
     */
    const RESOURCE_NOT_DELETED = 18;
    /**
     * Generated from protobuf enum <code>SCHEMA_VALIDATION_IGNORED = 19;</code>
     */
    const SCHEMA_VALIDATION_IGNORED = 19;
    /**
     * Generated from protobuf enum <code>SINGLE_INSTANCE_PROPERTY_TEMPLATE = 20;</code>
     */
    const SINGLE_INSTANCE_PROPERTY_TEMPLATE = 20;
    /**
     * Generated from protobuf enum <code>UNDECLARED_PROPERTIES = 21;</code>
     */
    const UNDECLARED_PROPERTIES = 21;
    /**
     * Generated from protobuf enum <code>UNREACHABLE = 22;</code>
     */
    const UNREACHABLE = 22;

    private static $valueToName = [
        self::CLEANUP_FAILED => 'CLEANUP_FAILED',
        self::DEPRECATED_RESOURCE_USED => 'DEPRECATED_RESOURCE_USED',
        self::DEPRECATED_TYPE_USED => 'DEPRECATED_TYPE_USED',
        self::DISK_SIZE_LARGER_THAN_IMAGE_SIZE => 'DISK_SIZE_LARGER_THAN_IMAGE_SIZE',
        self::EXPERIMENTAL_TYPE_USED => 'EXPERIMENTAL_TYPE_USED',
        self::EXTERNAL_API_WARNING => 'EXTERNAL_API_WARNING',
        self::FIELD_VALUE_OVERRIDEN => 'FIELD_VALUE_OVERRIDEN',
        self::INJECTED_KERNELS_DEPRECATED => 'INJECTED_KERNELS_DEPRECATED',
        self::MISSING_TYPE_DEPENDENCY => 'MISSING_TYPE_DEPENDENCY',
        self::NEXT_HOP_ADDRESS_NOT_ASSIGNED => 'NEXT_HOP_ADDRESS_NOT_ASSIGNED',
        self::NEXT_HOP_CANNOT_IP_FORWARD => 'NEXT_HOP_CANNOT_IP_FORWARD',
        self::NEXT_HOP_INSTANCE_NOT_FOUND => 'NEXT_HOP_INSTANCE_NOT_FOUND',
        self::NEXT_HOP_INSTANCE_NOT_ON_NETWORK => 'NEXT_HOP_INSTANCE_NOT_ON_NETWORK',
        self::NEXT_HOP_NOT_RUNNING => 'NEXT_HOP_NOT_RUNNING',
        self::NOT_CRITICAL_ERROR => 'NOT_CRITICAL_ERROR',
        self::NO_RESULTS_ON_PAGE => 'NO_RESULTS_ON_PAGE',
        self::REQUIRED_TOS_AGREEMENT => 'REQUIRED_TOS_AGREEMENT',
        self::RESOURCE_IN_USE_BY_OTHER_RESOURCE_WARNING => 'RESOURCE_IN_USE_BY_OTHER_RESOURCE_WARNING',
        self::RESOURCE_NOT_DELETED => 'RESOURCE_NOT_DELETED',
        self::SCHEMA_VALIDATION_IGNORED => 'SCHEMA_VALIDATION_IGNORED',
        self::SINGLE_INSTANCE_PROPERTY_TEMPLATE => 'SINGLE_INSTANCE_PROPERTY_TEMPLATE',
        self::UNDECLARED_PROPERTIES => 'UNDECLARED_PROPERTIES',
        self::UNREACHABLE => 'UNREACHABLE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Code::class, \Google\Cloud\Compute\V1\Warning_Code::class);

