<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/compute/v1/compute.proto

namespace Google\Cloud\Compute\V1\RouterNatLogConfig;

use UnexpectedValueException;

/**
 * Protobuf type <code>google.cloud.compute.v1.RouterNatLogConfig.Filter</code>
 */
class Filter
{
    /**
     * Generated from protobuf enum <code>ALL = 0;</code>
     */
    const ALL = 0;
    /**
     * Generated from protobuf enum <code>ERRORS_ONLY = 1;</code>
     */
    const ERRORS_ONLY = 1;
    /**
     * Generated from protobuf enum <code>TRANSLATIONS_ONLY = 2;</code>
     */
    const TRANSLATIONS_ONLY = 2;

    private static $valueToName = [
        self::ALL => 'ALL',
        self::ERRORS_ONLY => 'ERRORS_ONLY',
        self::TRANSLATIONS_ONLY => 'TRANSLATIONS_ONLY',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Filter::class, \Google\Cloud\Compute\V1\RouterNatLogConfig_Filter::class);

