<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/compute/v1/compute.proto

namespace Google\Cloud\Compute\V1\VpnTunnel;

use UnexpectedValueException;

/**
 * Protobuf type <code>google.cloud.compute.v1.VpnTunnel.Status</code>
 */
class Status
{
    /**
     * Generated from protobuf enum <code>ALLOCATING_RESOURCES = 0;</code>
     */
    const ALLOCATING_RESOURCES = 0;
    /**
     * Generated from protobuf enum <code>AUTHORIZATION_ERROR = 1;</code>
     */
    const AUTHORIZATION_ERROR = 1;
    /**
     * Generated from protobuf enum <code>DEPROVISIONING = 2;</code>
     */
    const DEPROVISIONING = 2;
    /**
     * Generated from protobuf enum <code>ESTABLISHED = 3;</code>
     */
    const ESTABLISHED = 3;
    /**
     * Generated from protobuf enum <code>FAILED = 4;</code>
     */
    const FAILED = 4;
    /**
     * Generated from protobuf enum <code>FIRST_HANDSHAKE = 5;</code>
     */
    const FIRST_HANDSHAKE = 5;
    /**
     * Generated from protobuf enum <code>NEGOTIATION_FAILURE = 6;</code>
     */
    const NEGOTIATION_FAILURE = 6;
    /**
     * Generated from protobuf enum <code>NETWORK_ERROR = 7;</code>
     */
    const NETWORK_ERROR = 7;
    /**
     * Generated from protobuf enum <code>NO_INCOMING_PACKETS = 8;</code>
     */
    const NO_INCOMING_PACKETS = 8;
    /**
     * Generated from protobuf enum <code>PROVISIONING = 9;</code>
     */
    const PROVISIONING = 9;
    /**
     * Generated from protobuf enum <code>REJECTED = 10;</code>
     */
    const REJECTED = 10;
    /**
     * Generated from protobuf enum <code>STOPPED = 11;</code>
     */
    const STOPPED = 11;
    /**
     * Generated from protobuf enum <code>WAITING_FOR_FULL_CONFIG = 12;</code>
     */
    const WAITING_FOR_FULL_CONFIG = 12;

    private static $valueToName = [
        self::ALLOCATING_RESOURCES => 'ALLOCATING_RESOURCES',
        self::AUTHORIZATION_ERROR => 'AUTHORIZATION_ERROR',
        self::DEPROVISIONING => 'DEPROVISIONING',
        self::ESTABLISHED => 'ESTABLISHED',
        self::FAILED => 'FAILED',
        self::FIRST_HANDSHAKE => 'FIRST_HANDSHAKE',
        self::NEGOTIATION_FAILURE => 'NEGOTIATION_FAILURE',
        self::NETWORK_ERROR => 'NETWORK_ERROR',
        self::NO_INCOMING_PACKETS => 'NO_INCOMING_PACKETS',
        self::PROVISIONING => 'PROVISIONING',
        self::REJECTED => 'REJECTED',
        self::STOPPED => 'STOPPED',
        self::WAITING_FOR_FULL_CONFIG => 'WAITING_FOR_FULL_CONFIG',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Status::class, \Google\Cloud\Compute\V1\VpnTunnel_Status::class);

