<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/compute/v1/compute.proto

namespace Google\Cloud\Compute\V1\SslPolicy;

use UnexpectedValueException;

/**
 * Protobuf type <code>google.cloud.compute.v1.SslPolicy.MinTlsVersion</code>
 */
class MinTlsVersion
{
    /**
     * Generated from protobuf enum <code>TLS_1_0 = 0;</code>
     */
    const TLS_1_0 = 0;
    /**
     * Generated from protobuf enum <code>TLS_1_1 = 1;</code>
     */
    const TLS_1_1 = 1;
    /**
     * Generated from protobuf enum <code>TLS_1_2 = 2;</code>
     */
    const TLS_1_2 = 2;

    private static $valueToName = [
        self::TLS_1_0 => 'TLS_1_0',
        self::TLS_1_1 => 'TLS_1_1',
        self::TLS_1_2 => 'TLS_1_2',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(MinTlsVersion::class, \Google\Cloud\Compute\V1\SslPolicy_MinTlsVersion::class);

