<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/compute/v1/compute.proto

namespace Google\Cloud\Compute\V1\Interconnect;

use UnexpectedValueException;

/**
 * Protobuf type <code>google.cloud.compute.v1.Interconnect.LinkType</code>
 */
class LinkType
{
    /**
     * Generated from protobuf enum <code>LINK_TYPE_ETHERNET_100G_LR = 0;</code>
     */
    const LINK_TYPE_ETHERNET_100G_LR = 0;
    /**
     * Generated from protobuf enum <code>LINK_TYPE_ETHERNET_10G_LR = 1;</code>
     */
    const LINK_TYPE_ETHERNET_10G_LR = 1;

    private static $valueToName = [
        self::LINK_TYPE_ETHERNET_100G_LR => 'LINK_TYPE_ETHERNET_100G_LR',
        self::LINK_TYPE_ETHERNET_10G_LR => 'LINK_TYPE_ETHERNET_10G_LR',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(LinkType::class, \Google\Cloud\Compute\V1\Interconnect_LinkType::class);

